### ISSUE TITLE
UI Automation doesn't work

### ISSUE THREAD

**Issue by vadim1996wolf** [saucepleez/taskt#101]
# UI Automation and Element Recorder issue

*Element recorder* can't catch an element of a window properly. For example, instead of num9 button in calculator, it catches minus button. In some cases, it cathes an element of win10. Also is it possible to find System Explorer?

*Click UI item* and *Get UI item* work correctly.

When I try to automate *All Windows* and any of three actions (*click, get value, exists*) , script throws the  following exception after the execution:

```2019-02-07 12:03:18.117 +03:00 [INF] Running Line 1: UI Automation [Left Click element in window 'All Windows']
2019-02-07 12:03:18.492 +03:00 [INF] Result Code: Error
2019-02-07 12:03:18.493 +03:00 [INF] Error: System.Exception: System.ArgumentOutOfRangeException: Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index
   в System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   в System.Collections.Generic.List`1.get_Item(Int32 index)
   в taskt.Core.AutomationCommands.UIAutomationCommand.SearchForGUIElement(Object sender, String variableWindowName) в C:\Users\username\Desktop\taskt-master\taskt\Core\AutomationCommands.cs:строка 2903
   в taskt.Core.AutomationCommands.UIAutomationCommand.RunCommand(Object sender) в C:\Users\username\Desktop\taskt-master\taskt\Core\AutomationCommands.cs:строка 2931
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\Users\username\Desktop\taskt-master\taskt\Core\AutomationEngine.cs:строка 268
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\Users\username\Desktop\taskt-master\taskt\Core\AutomationEngine.cs:строка 295
   в taskt.Core.AutomationEngineInstance.ExecuteScript(String data, Boolean dataIsFile) в C:\Users\username\Desktop\taskt-master\taskt\Core\AutomationEngine.cs:строка 153
```

**Comment by vadim1996wolf** [comment]
✔ Resolved by changing screen scale to 100%.

So how can i find System Explorer using UI Automation or another?
And could you add an update button to update lists of automation elements and properties? For example, i opened or closed a window and it is still in the list of items.

**Comment by vadim1996wolf** [comment]
It works now but can't process boolean properties.
```
2019-02-07 15:21:56.604 +03:00 [INF] Error: System.Exception: System.ArgumentException: Значение PropertyCondition для свойства "AutomationElementIdentifiers.IsEnabledProperty" должно быть "Boolean".
   в System.Windows.Automation.PropertyCondition.Init(AutomationProperty property, Object val, PropertyConditionFlags flags)
   в System.Windows.Automation.PropertyCondition..ctor(AutomationProperty property, Object value)
   в taskt.Core.AutomationCommands.UIAutomationCommand.CreatePropertyCondition(String propertyName, String propertyValue) в C:\Users\USERNAME\Desktop\taskt-master\taskt\Core\AutomationCommands.cs:строка 2841
   в taskt.Core.AutomationCommands.UIAutomationCommand.SearchForGUIElement(Object sender, String variableWindowName) в C:\Users\USERNAME\Desktop\taskt-master\taskt\Core\AutomationCommands.cs:строка 2890
   в taskt.Core.AutomationCommands.UIAutomationCommand.RunCommand(Object sender) в C:\Users\USERNAME\Desktop\taskt-master\taskt\Core\AutomationCommands.cs:строка 2931
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\Users\USERNAME\Desktop\taskt-master\taskt\Core\AutomationEngine.cs:строка 268
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\Users\USERNAME\Desktop\taskt-master\taskt\Core\AutomationEngine.cs:строка 295
   в taskt.Core.AutomationEngineInstance.ExecuteScript(String data, Boolean dataIsFile) в C:\Users\USERNAME\Desktop\taskt-master\taskt\Core\AutomationEngine.cs:строка 153
```

**Comment by saucepleez** [comment]
Hi:

1) Can you share a screenshot of your current UI Automation Command that is giving problems?  It looks like you are searching for a Boolean value but the value provided isn't type Boolean.  This may be a bug as the items are technically stored as string and may need additional conversion. It would be even better if you could share your script file (you can rename it to .txt and attach here) so I can try to replicate.

2) What do you mean by "Find System Explorer"?  Can you elaborate on what you are trying to do?

**Comment by vadim1996wolf** [comment]
Hi!

1. When a boolean property (checkbox) is enabled, it throws exception, that PropertyCondition must be "Boolean". There is the screenshot at the end.

2. There is only one System Explorer on Windows:
C:\Windows\explorer.exe
Taskt can't process (click or another) an element of System Explorer window. I have 10 opened explorer windows and no one is at the element list.

![image](https://user-images.githubusercontent.com/13113616/52464736-15f0da80-2b8d-11e9-9e98-120fae5c2ec3.png)

**Comment by saucepleez** [comment]
Thank you for the clarification.  I was able to replicate your first issue and I am working on addressing it now.

**Comment by saucepleez** [comment]
You should be able to address Windows Explorer windows in the next release.

**Comment by vadim1996wolf** [comment]
Thanks a lot!
