### ISSUE TITLE
About creating Functions

### ISSUE THREAD

**Issue by diweshtanwar** [saucepleez/taskt#104]
Hi Team- How can i create functions in the same automation command files
Means i want my code as small small functions. 
Any Idea please

**Comment by saucepleez** [comment]
You can create a command and then call it from another command using `Task Commands` > `Run Task`

**Comment by diweshtanwar** [comment]
Ok but suppose if we want to pass some variables value from one  task to another task. Kindly suggest on this.
And thanks for your reply

**Comment by saucepleez** [comment]
Hello,

Currently there is not a built in way to do that, we will look at adding it for the next release.

**Comment by saucepleez** [comment]
@diweshtanwar I have added this to the DEV branch and will further test it.

**Comment by diweshtanwar** [comment]
Hi saucepleez- can you tell me on which archeture you develop this project as I am very new to .net development

**Comment by saucepleez** [comment]
> Hi saucepleez- can you tell me on which archeture you develop this project as I am very new to .net development

This is a WinForms project using .NET Framework 4.8
