### ISSUE TITLE
Exit loop within nested loop list

### ISSUE THREAD

**Issue by rafernandezsan** [saucepleez/taskt#117]
Hello.

When trying to exit from a nested "Loop List" using the command "Exit Loop", it comes out of all the loops and not just from the loop that the command has been invoked on.

**Comment by saucepleez** [comment]
@rafernandezsan  Thank you for reporting this issue. We will review and revert in case of any concerns.

**Comment by saucepleez** [comment]
@rafernandezsan  This issue should be fixed now and is present in the DEV branch if you want to build/test
