### ISSUE TITLE
Loop dataset Excel

### ISSUE THREAD

**Issue by Intizar7** [saucepleez/taskt#118]
![Ekran](https://user-images.githubusercontent.com/27590430/57213895-d5b8c100-6ff0-11e9-87b8-bac9e11677d0.PNG)

1.What do we need to include in the loop that appears above to get the contents of the lines in the Excel ?
2.Automation Anywhere To do the same operation;
 "Start Loop "Each row in an Excel dataset of Session: S1" 
"Comment: Please enter your commands to loop. Use $Excel Column$ variable for each row in Excel"

The expression shown above uses "variable (Excel Column)" to retrieve the value of the data in each row.
We want to make the same process in the Taskt application and Could you to do provide feedback about how we can do it.

**Comment by saucepleez** [comment]
@Intizar7  Hello, thank you for your expressed interest.  We need to re-work the dataset commands completely to account for things like the installed driver (ACE 8, 12, 16, SQL, etc).  The command you are handling was an early first attempt at creating datasets.   If you want to do work with Excel, I would recommend using the standard Excel functionality:


![image](https://user-images.githubusercontent.com/5113950/57232180-13661b80-6fea-11e9-8f1f-b4bce8a59c8e.png)

![image](https://user-images.githubusercontent.com/5113950/57232203-1bbe5680-6fea-11e9-8e99-a8f3f8c54fd3.png)

![image](https://user-images.githubusercontent.com/5113950/57232423-8d96a000-6fea-11e9-8f0b-07b64668884d.png)

![image](https://user-images.githubusercontent.com/5113950/57232430-91c2bd80-6fea-11e9-9436-5047d954f49b.png)

![image](https://user-images.githubusercontent.com/5113950/57232442-95eedb00-6fea-11e9-81ed-9de55fae39e6.png)

![image](https://user-images.githubusercontent.com/5113950/57232450-99826200-6fea-11e9-9418-4cf60ef984e4.png)
[Excel Loop Sample.txt](https://github.com/saucepleez/taskt/files/3148421/Excel.Loop.Sample.txt)

**Comment by saucepleez** [comment]
Closing due to no reply.  Please open a new issue if you have any concerns.

**Comment by Intizar7** [comment]
Thank you for your return. I don't want to go by location when I'm recording. I want to know what that object or program . Could you to do provide feedback about how we can do it.
