### ISSUE TITLE
Taskt CI/CD

### ISSUE THREAD

**Issue by atotalnoob** [saucepleez/taskt#123]
Hi,

@saucepleez Could you please add me to your Azure Devops instance and I will start setting up a CI/CD pipeline for Taskt? 

You can automatically add releases to github release page, too.

What would you like to add to the pipeline? Here is some ideas:

1. Auto create release notes
2. Auto sign binaries
3. Auto increment versions

**Comment by saucepleez** [comment]
@atotalnoob There currently is no Azure DevOps instance for this project.

**Comment by atotalnoob** [comment]
Why not, the first 5 users are free, so just create it and then add me

**Comment by saucepleez** [comment]
pipeline has been enabled

**Comment by atotalnoob** [comment]
@saucepleez you have all three items implemented

**Comment by saucepleez** [comment]
@atotalnoob The latest release 3.2.0.0 was built, signed and deployed automatically.  The only thing not being managed yet is the build version

**Comment by atotalnoob** [comment]
So it's not 100% done. 

2 out of 3 isn't completely finished
