### ISSUE TITLE
 error reading scanned pdf

### ISSUE THREAD

**Issue by merveAltili** [saucepleez/taskt#125]
Hello! How can I read "Scraned" pdf with Pdf Extractoin?

**Comment by saucepleez** [comment]
@merveAltili You cannot read a scanned PDF as the PDF parser is looking for electronic data.  You can try to do OCR on the image text, otherwise, you will probably need to look at using cloud services.  

We can add a specific command for "Document Analysis" if required.

**Comment by merveAltili** [comment]
Thank you so much. 
So, if you have a sample .xml about the database command, would you share it?

**Comment by merveAltili** [comment]
I've done it with no need for an example :) Thank you very much I wish you good work.
