### ISSUE TITLE
HTTP Error 500.19

### ISSUE THREAD

**Issue by Vitaliy-B** [saucepleez/taskt#126]
I am trying to start taskt server using this [instruction](https://github.com/saucepleez/tasktServer/wiki/Sample-tasktServer-Deployment-using-IIS)

I get the following error: ![error](https://monosnap.com/image/A4yVG5FX0eoLQ5Ny61NINtal7wLVRx)

Error code leads me to the following [page.](https://support.microsoft.com/en-us/help/942055/http-error-500-19-error-when-you-open-an-iis-7-0-webpage)

![Alt text](https://monosnap.com/image/5bBLAeuT9tUPx2kmvSBXJCtz5DqQos)

So it tells that it's the problem with ApplicationHost.config file or Web.config file.
But `ApplicationHost.config` is not present, and `Web.config` was not modified. Here is it's [content.](https://pastebin.com/q6g3KwpA)

What should I do?

**Comment by saucepleez** [comment]
Did you check that you added the permissions to the parent folder?

**Comment by Vitaliy-B** [comment]
yes, of course, I added permissions. It does not help

**Comment by saucepleez** [comment]
Ok.  Did you set up your application pool identity?  https://blogs.msdn.microsoft.com/rohithrajan/2018/03/13/500-19-error-or-502-5-error-when-hosting-asp-net-core-2-application-inside-iis/

**Comment by saucepleez** [comment]
Closed due to no response
