### ISSUE TITLE
UI Automation Error 

### ISSUE THREAD

**Issue by mrdealba15** [saucepleez/taskt#127]
Hi!, when I want to use the UI Automation, appears this error: 

![Error](https://user-images.githubusercontent.com/26585138/59204035-6856fd80-8b65-11e9-9406-2c3321d7c890.PNG)

**Comment by saucepleez** [comment]
Hi @mrdealba15 

What were you doing to cause this error?  Can it be reproduced?

**Comment by mrdealba15** [comment]
it just when I double click in the option "UI Automation", when I reopen it works the first time that I used but fail again later.

**Comment by BryannLuna** [comment]
I found the same problem

**Comment by BryannLuna** [comment]
![image](https://user-images.githubusercontent.com/40610606/59310769-100b2300-8c6d-11e9-8905-7bf23c1d80c0.png)

**Comment by saucepleez** [comment]
I have added additional error handling and reorganized the code.  Please let me know if you continue to encounter errors, if so, please document the steps to recreate the error.
