### ISSUE TITLE
errror while building source code on my machine

### ISSUE THREAD

**Issue by naga1992** [saucepleez/taskt#13]
When i am building the source code on my machine i am gettting the error 

Source file 'taskt-master\taskt\Core\SocketServer.cs' could not be found.

**Comment by saucepleez** [comment]
Thanks for reporting this, it looks like I never actually pushed the socket server code.

You can comment out any related socket server calls, I am working on the orchestrator portion in a seperate repo.

I will push the socket server code ASAP.

**Comment by saucepleez** [comment]
Code has been merged and updated.  Please review and open a new issue if you still see the error.
