### ISSUE TITLE
UI Automation

### ISSUE THREAD

**Issue by Vitaliy-B** [saucepleez/taskt#131]
When I am trying to use UI Automation, it brings me error

![image](https://user-images.githubusercontent.com/3762223/59604379-af6c6200-9114-11e9-95b9-1a679c1a6942.png)

Error message:

System.ArgumentOutOfRangeException: Index out of range. The index must be a positive number, and its size must not exceed the size of the collection.
Parameter name: index

Original:

System.ArgumentOutOfRangeException: Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index
   в System.Collections.ArrayList.get_Item(Int32 index)
   в System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
   в System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   в taskt.Core.Automation.Commands.UIAutomationCommand.UIAType_SelectionChangeCommitted(Object sender, EventArgs e)
   в taskt.Core.Automation.Commands.UIAutomationCommand.ActionParametersGridViewHelper_MouseEnter(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnMouseEnter(EventArgs e)
   в System.Windows.Forms.DataGridView.OnMouseEnter(EventArgs e)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.DataGridView.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Full text:
https://pastebin.com/sMYqkCtD

**Comment by saucepleez** [comment]
Someone else reported this issue, I believe it has since been fixed.  Are you able to review the latest from the DEV branch? Otherwise I can push a new build that you can test with.

**Comment by Vitaliy-B** [comment]
ok, thanks, code from dev branch do not throw this exception

**Comment by saucepleez** [comment]
Ok, we will look to build 3.0 end of week
