### ISSUE TITLE
OCR not working

### ISSUE THREAD

**Issue by Vitaliy-B** [saucepleez/taskt#132]
I installed OneNote, but I still can't use OCR. It gives me an error:

2019-06-19 14: 33: 18.817 +03: 00 [INF] Creating App Instance Tracking List
2019-06-19 14: 33: 18.817 +03: 00 [INF] Running Line 1: Add Variable [Assign '' to New Variable 'v1']
2019-06-19 14: 33: 19.108 +03: 00 [INF] Skipping Line 2: OCR 'C: \ Users \ Vitaliy \ Documents \ taskt \ scrsh01.png' and apply result to 'v1'
2019-06-19 14: 33: 19.108 +03: 00 [INF] Running Line 3: OCR 'F: \ test.jpg' and apply result to 'v1'
2019-06-19 14: 33: 22.439 +03: 00 [INF] Result Code: Error
2019-06-19 14: 33: 22.439 +03: 00 [INF] Error: System.Exception: System.FormatException: The input string had an invalid format.
   in System.Number.ParseSingle (String value, NumberStyles options, NumberFormatInfo numfmt)
   in System.Single.Parse (String s)
   in OneNoteOCRDll.OneNoteOCR.AttributeToFloat (XElement node, String name)
   in OneNoteOCRDll.OneNoteOCR. <OcrTexts> d__4.MoveNext ()
   in System.Linq.Buffer`1..ctor (IEnumerable`1 source)
   in System.Linq.Enumerable.ToArray [TSource] (IEnumerable`1 source)
   in taskt.Core.Automation.Commands.OCRCommand.RunCommand (Object sender) in  taskt \ Core \ Automation \ Commands \ OCRCommand.cs: line 49
   in taskt.Core.Automation.Engine.AutomationEngineInstance.ExecuteCommand (ScriptAction command) in  taskt \ Core \ Automation \ Engine \ AutomationEngineInstance.cs: line 296
   in taskt.Core.Automation.Engine.AutomationEngineInstance.ExecuteCommand (ScriptAction command) in  taskt \ Core \ Automation \ Engine \ AutomationEngineInstance.cs: line 323
   in taskt.Core.Automation.Engine.AutomationEngineInstance.ExecuteScript (String data, Boolean dataIsFile) in   taskt \ Core \ Automation \ Engine \ AutomationEngineInstance.cs : line 180

**Comment by saucepleez** [comment]
So I am not readily responsible from this library as it comes from the OneNote OCR project, https://github.com/ignatandrei/OneNoteOCR/tree/master/OneNoteOCRDll.

However, taking a look at your path, it looks like you have extra spaces.  My logs look like this:


![ocrtest](https://user-images.githubusercontent.com/5113950/59768986-47805d80-9273-11e9-87b4-1ff66f87f071.png)

![image](https://user-images.githubusercontent.com/5113950/59768967-40594f80-9273-11e9-9914-9d041e19bc04.png)


[OCR Test.xml.txt](https://github.com/saucepleez/taskt/files/3306260/OCR.Test.xml.txt)

**Comment by Vitaliy-B** [comment]
These extra spaces were added when I was translating error message to English. Originally path is ok
