### ISSUE TITLE
UI Automation Element Recorder error

### ISSUE THREAD

**Issue by merveAltili** [saucepleez/taskt#133]
![UI Automation Error](https://user-images.githubusercontent.com/27894231/59768442-115fcf80-92ad-11e9-8b31-3756562656cb.png)
I get this error when I click on a field on the web page where the element record in UI automation is located. What is the cause of the error?

**Comment by saucepleez** [comment]
What type of field were you clicking? You should not use UI automation for Web automation.

**Comment by merveAltili** [comment]
Thank you
