### ISSUE TITLE
Send Advanced Keystrokes - Alt key error

### ISSUE THREAD

**Issue by merveAltili** [saucepleez/taskt#135]
When I send a command to press the left **alt+e** keys, it does not perform the operation. What is the reason?

![image](https://user-images.githubusercontent.com/27894231/60092541-f62f0d00-974f-11e9-8b9a-f4411270c94e.png)

**Comment by saucepleez** [comment]
This is working fine with me for notepad, ex:

![image](https://user-images.githubusercontent.com/5113950/60112173-5799b080-973d-11e9-9355-bd3ce96301b9.png)

results in:

![image](https://user-images.githubusercontent.com/5113950/60112249-75671580-973d-11e9-85cd-6cd2fac02262.png)

Also, Key Press works fine as well:
![image](https://user-images.githubusercontent.com/5113950/60112327-93347a80-973d-11e9-9462-3e6ccf1203d9.png)

I would suggest checking your target window and additionally check that from its current state you can validly press ALT + E

**Comment by merveAltili** [comment]
![image](https://user-images.githubusercontent.com/27894231/60158794-7b6efc00-97fa-11e9-958a-1d8397baa8c0.png)

![image](https://user-images.githubusercontent.com/27894231/60158839-8d509f00-97fa-11e9-9212-d6fa48f4cb97.png)

When I try Alt [Menu] + E, € shows me this statement. Actually, my goal here is to create a 2nd line and press the left bottom + e keys, which is the shortcut used on this site. So my goal was to create a second line, but as shown in the picture, it shows me the € symbol. I'd appreciate it if you helped.

**Comment by saucepleez** [comment]
Hello,

The following key combination is working for me to open the chrome menu:

![image](https://user-images.githubusercontent.com/5113950/62014241-92439e00-b16c-11e9-9c60-ed9b9d2ac2b9.png)
