### ISSUE TITLE
A new internet explorer window generated after logon

### ISSUE THREAD

**Issue by heolc** [saucepleez/taskt#137]
After logon to a system using IE, there will be another IE window popping to load the page instead of the original IE window.
I know how to refer to instance variable when creating a browser using taskt, but
do not know how to catch the new instance for IE window popped up/or another new popped up? Thanks.

**Comment by saucepleez** [comment]
Are you using the IE Browser Commands or Web Browser Commands?

**Comment by heolc** [comment]
I used "Web Browser Commands">>"Create Browser">>"Browser Engine Type" = IE

There will be two separate IE windows after logon to the system.
I know how to use VBA to identify the IE window by finding their url
But for taskt, seems need to use the instance name to identify the IE window in order to carry out element action. As the new popped IE window didn't have any instance name assigned before, any suggested solution to this issue

**Comment by saucepleez** [comment]
Hello,

I have added a new command called **Switch Browser Window** which will switch the driver window based on your selected options, typically either the new window URL or the new window title.

![image](https://user-images.githubusercontent.com/5113950/61999130-b75ee080-b088-11e9-8df4-65c738f1086f.png)

[Switch Window Test Script.txt](https://github.com/saucepleez/taskt/files/3438551/Switch.Window.Test.Script.txt)

**Comment by heolc** [comment]
Thanks for updating and it works. Appreciate it.
