### ISSUE TITLE
Database Connections

### ISSUE THREAD

**Issue by karthikshashi** [saucepleez/taskt#138]
Wonderful work that you have done. Could you please add a Database functionality as well in your upcoming release. Also some text file options to trim / parse text will be of great help.

**Comment by saucepleez** [comment]
Hello, 

We can look at adding Trim text. What do you mean by parse text?  Also how do you imagine the database functionality working?

**Comment by humbertoanascimento** [comment]
Hi,

Could I participate this discussion? I work with some RPA tools.

The database could be compatible with generic driver connections, like DBeaver: you define the driver path the program and set others generals and specific configurarions. Thus is possible to use any desired driver.

Besides DB connection, is need some exception treatment that could be more generic, like a try-catch. This way is possible to define the behavior of automation when this case occur.

**Comment by saucepleez** [comment]
Hi,

Sure.  So to do this we can look at implementing 4 commands (off the top):

- Connect
- Execute Stored Procedire
- Execute Query
- Disconnect

In terms of try-catch, we can look at implementing that for all commands, that should probably be a separate work item.

**Comment by shiddugmail** [comment]
This is a good news 

Thank you,
Regards,
Shiddu Mageppa

**Comment by karthikshashi** [comment]
> Hi,
> 
> Sure. So to do this we can look at implementing 4 commands (off the top):
> 
> * Connect
> * Execute Stored Procedire
> * Execute Query
> * Disconnect
> 
> In terms of try-catch, we can look at implementing that for all commands, that should probably be a separate work item.

- For the Connect action, it will be good to have information collected in different fields and then join them to create a connection string at real time. The password field can then be invisible / encrypted.
- In the Execute Stored Procedure, the connection name will need to be available to specify which DB stored connection to run the query on.
- Execute query action could be similar to Execute Stored Procedure and will be good to subscribe input from the output of a previously run object / action in the workflow.
- Disconnect - Once a query is completed, session generally terminates.

Compatibility : SQL first and My SQL later? 

This will be too good a functionality to have and thanks a ton.

**Comment by saucepleez** [comment]
@karthikshashi 

Agreed.  I think for the connect command we can use the data link builder:

![image](https://user-images.githubusercontent.com/5113950/62001129-150a2180-b0b7-11e9-8cda-47ab23e5c832.png)

This way we can support compatibility for most databases -- users will simply need to install the providers onto their machine.  I started work on this but ran into a few bumps

**Comment by saucepleez** [comment]
Ok @karthikshashi, I have added the define connection and initial query commands using OLEDB.

Here is sample SQL Data Source:
![image](https://user-images.githubusercontent.com/5113950/62087137-b1a2ff80-b22e-11e9-908b-f6b41c6e998c.png)

Here is sample command to retrieve data:
![image](https://user-images.githubusercontent.com/5113950/62087126-a2bc4d00-b22e-11e9-834c-2e56a4641c39.png)

Here is the result:
![image](https://user-images.githubusercontent.com/5113950/62087204-ef078d00-b22e-11e9-8363-57bf6cefca4a.png)

**Comment by saucepleez** [comment]
@karthikshashi @humbertoanascimento  I have added database commands as well as try/catch/finally/end try.  Please open new issues if you need help or encounter any problems, thanks.

**Comment by karthikshashi** [comment]
As fast as lightening !!! Can't be thankful enough Sir. And I will download
the latest release. Thank you so much.

**Comment by karthikshashi** [comment]
Sir could you please also let me know how I can get a copy of the latest
version. Thanks.

**Comment by humbertoanascimento** [comment]
@saucepleez Its stunning your agility and fast answers! I will try the latest version tonight. Very thanks for these new features!

**Comment by saucepleez** [comment]
@humbertoanascimento  @karthikshashi  Are you building from source code? If not, I will further test and release a compiled binary.

**Comment by karthikshashi** [comment]
Sir I'm not touching source code yet. If it doesn't hurt you too much a
compile will be awesome.

**Comment by saucepleez** [comment]
@karthikshashi  I will build a 3.1.0.0 binary tonight EST.

**Comment by saucepleez** [comment]
@karthikshashi Please see latest release preview

**Comment by karthikshashi** [comment]
Thank you sir. I got a Symantec security warning when I downloaded the file
though.

**Comment by saucepleez** [comment]
@karthikshashi

What was the issue Symantec gave?  This was the first build through Azure Pipelines.  Binary should be signed.

**Comment by atotalnoob** [comment]
@saucepleez test the binary in a vm

**Comment by saucepleez** [comment]
@atotalnoob  There is no issue with the binary, the issue is with Symantec probably because it has not seen this file "in the wild" yet.  Symantec does not offer whitelisting for developers so the only course of action will be for @karthikshashi to manually build the project until Symantec begins to trust the zip file.
