### ISSUE TITLE
Can Taskt run many robot instances in parallel ? 

### ISSUE THREAD

**Issue by asakre** [saucepleez/taskt#140]
I want to design a flow which will be ran/triggered more than 10 times per minute based on a query in a database.
Does Taskt support parallel robots ?
Can Taskt connect to a Mysql database to select and insert data ?

**Comment by saucepleez** [comment]
Hello,

Currently you can use task scheduler to launch multiple taskt instances.   You can quickly schedule by selecting Script Actions > Schedule to create a schedule, then editing it from within the task scheduler.

![image](https://user-images.githubusercontent.com/5113950/61422413-8b4d9d80-a8d9-11e9-9618-ac6ae8e7e8e6.png)

It is possible to execute robots in parallel but only if you are using certain commmands -- anything that needs to activate window handles or manipulate data on-screen will be problematic for running in parallel.  I believe web browser commands and other internal commands should work fine.

There is a **database run query** command but it is disabled by default and is limited in functionality.  If working with databases is required, we should probably rebuild that logic to support multiple databases and functions.

Based on my response please let me know the requirements if we should expand into more functionality.
