### ISSUE TITLE
rest api parse json

### ISSUE THREAD

**Issue by merveAltili** [saucepleez/taskt#141]
![image](https://user-images.githubusercontent.com/27894231/61631834-0de8ab00-ac94-11e9-86ee-c32cc3cb6fea.png)

How do I parse the json expression that appears in this image. Ex: net_total> = 1000 I want to list the descriptions of those.

**Comment by saucepleez** [comment]
Hello,

This sample shows how to parse Json based on your requirement, if you can post a sample json array, I can reply with a sample script.  
https://github.com/saucepleez/taskt/blob/master/taskt/Sample%20Scripts/Parse%20JSON%20Sample.xml

You should be able to do something like this to select the items from the array:

![image](https://user-images.githubusercontent.com/5113950/61999195-de69e200-b089-11e9-861e-bae5004ae26f.png)

Then you can loop the new variable which will contain the data:

![image](https://user-images.githubusercontent.com/5113950/61999201-eb86d100-b089-11e9-9d89-f7f7ac1bdb93.png)

You can then use ParseJson command to parse out each individual item in the list.

**Comment by merveAltili** [comment]
![image](https://user-images.githubusercontent.com/27894231/62038706-e4350400-b1fe-11e9-9833-847758df71c4.png)
I tried, but I failed again. I would be glad if you help.

**Comment by saucepleez** [comment]
Can you please post some sample string JSON?

**Comment by saucepleez** [comment]
I created a sample based on the input you indicated.  The JSON selector is essentially a shortcut, but you can loop this the longer way.  Download the following sample, change .txt to .xml.

[JSON PARSE.txt](https://github.com/saucepleez/taskt/files/3442896/JSON.PARSE.txt)

**Comment by merveAltili** [comment]
Sample worked successfully thank you very much .
