### ISSUE TITLE
Web scrap multiple titles from youtube

### ISSUE THREAD

**Issue by heolc** [saucepleez/taskt#151]
i am able to use element action>>find element by css selector to web scrap a video tile from youtube trending feed but unable to do so for multiple tiltles.
seems it didn't work when using "find elements"
i wonder if i can use taskt do web scrap multiple video titles from youtube
![image](https://user-images.githubusercontent.com/9914455/63404473-f9740b80-c415-11e9-9d39-4073e7b414b9.png)

![image](https://user-images.githubusercontent.com/9914455/63404496-0c86db80-c416-11e9-8300-ebe9225191fc.png)

**Comment by saucepleez** [comment]
Hello,

Did you give the page time enough to load?

**Comment by heolc** [comment]
i forgot that. Let me try. Thanks.
