### ISSUE TITLE
Activity missing - Integration with Database

### ISSUE THREAD

**Issue by Sasidhar23** [saucepleez/taskt#154]
I haven't found any activity related to integration with database in taskt.
Could someone help me with the same..

TIA,
Sasidhar

**Comment by saucepleez** [comment]
For anyone else looking for a database sample, please take a look at [Database Integration.xml](https://github.com/saucepleez/taskt/blob/development-branch/taskt/Sample%20Scripts/3.x%20Use%20Case%20Samples/Database%20Integration%20%5B3.1.0.0%5D.xml)
