### ISSUE TITLE
Generate executable for automation

### ISSUE THREAD

**Issue by rafernandezsan** [saucepleez/taskt#156]
Hello.
Is it possible to generate an executable file with the process steps from the builder? this way, it can be executed without the necessity of the automation engine?

**Comment by saucepleez** [comment]
Hi,

Why would you not just invoke the executable file and pass the script file path as an argument?

**Comment by rafernandezsan** [comment]
Hello.
Thanks for the advise. In this case, this will open the Taskt app and run the script from the builder, right?
I just want a compiled file with the process.
if it is not possible right now, is it planned to be implemented?

**Comment by saucepleez** [comment]
> Hello.
> Thanks for the advise. In this case, this will open the Taskt app and run the script from the builder, right?
> I just want a **compiled file** with the process.
> if it is not possible right now, is it planned to be implemented?

No, the executable that launches the builder also accepts a parameter for a script path. If a valid script  path is provided, the automation engine will invoke the script without showing the builder. In this case, the debug window will appear, script will execute, then the debug window will close and the application will exit.  The builder is only shown when a valid script path has not been provided.

You can test this by copying a script into the folder where the taskt executable file is: 
![image](https://user-images.githubusercontent.com/5113950/66249368-1e8bb780-e700-11e9-9409-95905a7397d0.png)

You can then invoke it directly from the command line:
![image](https://user-images.githubusercontent.com/5113950/66249356-e7b5a180-e6ff-11e9-999d-f1a801039839.png)

If this is not solving your issue, would you mind explaining what you mean by "Compiled File" or describing the intended functionality?

**Comment by wbv-profile** [comment]
@saucepleez also he can develop simple application for example which strores xml files and calls taskt.exe with main xml as an argument.
