### ISSUE TITLE
It stops when you use the End key.

### ISSUE THREAD

**Issue by taktd1130** [saucepleez/taskt#16]
Hello, saucepleez
I use taskt, but when I want to scroll to the bottom of the screen
If you enter {END}, processing stops halfway.
Is there any good solution?

**Comment by saucepleez** [comment]
Hello,

We will move the functionality to the Pause/Break key instead.  I will update the repository once this is complete.  Are you building the solution yourself or using a released version?

**Comment by saucepleez** [comment]
Please review the latest release or source code if needed:

https://github.com/saucepleez/taskt/releases/tag/v1.5.2.0

**Comment by taktd1130** [comment]
Thank you!

We were able to achieve the expected behavior.
I appreciate that you corrected the program.

I would like to offer RPA-based services in Japan.
We focus on taskt as one of several RPA tools.
In future I would like to try taskt in Japanese.

// I am not a developer, but I'm planning to learn C # now :)
