### ISSUE TITLE
What are the system requirements?

### ISSUE THREAD

**Issue by Lemondropz** [saucepleez/taskt#163]
Hi,

I'm interested in implementing this at my organization, and part of our application review policy includes referencing documented system requirements.

Are such requirements documented somewhere, and if not can someone please share what they are?

Thanks!

**Comment by atotalnoob** [comment]
There isn't a hard system requirement. It kind of depends on your specific tasks and software you are automating. For example, if your automating a piece of software that requires 8gb of ram, 2 vcpu, you would need that as the minimum.

Standalone, I'd say probably windows 10, 1 GB ram and 1 vcpu.

**Comment by saucepleez** [comment]
Hello,

As mentioned by @atotalnoob it depends on how intensive your process is and which software is requiring automation.  I would recommend a bit more RAM than that if possible but that should work fine.

This application is built against .NET Framework 4.8 and should be compatible with Windows 7/8.1/10/2012 Server/2016 Server. (review the requirements here: https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements).

OS: Windows Server 2012, Windows Server 2016, Windows 10
Processor: 3 GHz or better
RAM: 2GB or better
Hard Disk: 200MB or better
Browser: IE11, Chrome 50+

**Comment by atotalnoob** [comment]
@saucepleez I would not recommend windows 7, since it is reaching EOL in January. 

I still believe 1gb/1vcpu is sufficient for the minimum requirements. I would agree 2gb ram would be a recommended system spec

**Comment by Lemondropz** [comment]
Thanks for the help, all!
