### ISSUE TITLE
Taskt enhancements

### ISSUE THREAD

**Issue by Hassan-Ali123** [saucepleez/taskt#169]
Hi team! I am exploring taskt for two days. There are some enhancements I want to be added to taskt:
1. Debugging options like breakpoints, Step In, Step Over, etc. should be added for detecting the point of error.
2. Can we create our own workflow in taskt, as we do in UiPath Studio?
3. Taskt does not provide output window for the processing details like UiPath or other Automation tools, although it logs the processing details in separate folder, but at least an output window option should be added so that users can easily know the error details.
4. Does not log error messages or exceptions in user-friendly language.
5. No help provided on youtube in the form of video lectures.

**Comment by saucepleez** [comment]
Hello,

Please see replies below.  Please open additional issues for each enhancement you would like to request after reading my responses below.

1. There is a "Pause Before Execution" option which should act as a breakpoint. You can right-click each command and set it to pause which will act as a "Step".  We can look at adding an enhancement to automatically Pause on every command so you do not have to set the flag on each command if required.

![image](https://user-images.githubusercontent.com/5113950/70636963-6e0cc900-1c04-11ea-8375-259c381154f2.png)


2.  What do you mean by Workflow?  Currently we support sequences which are a group of commands together.  Your bot will invoke the sequence which will execute the commands.  You can also run commands from another external file. You will need to elaborate on the intended functionality, giving it as a requirement.

3.  You can click on the taskt icon in the engine window to show the debugging logs or set the option under "Settings" > "Automation Engine" Tab > "Show Advanced Debug Logs During Execution" to TRUE .  From the engine window, you can double-click any of them to show the underlying log.
![image](https://user-images.githubusercontent.com/5113950/70637262-effcf200-1c04-11ea-9d69-9c0b308b8ad4.png)

![image](https://user-images.githubusercontent.com/5113950/70637379-20dd2700-1c05-11ea-897a-36d9ff4ef3d3.png)

4.  It depends on what the error is.  There is a catch-all for exceptions that were not explicitly handled.  There can be a variety of reasons for an error to occur.  Not sure how you define "User Friendly" language, we should see some specific examples, especially if you have come across errors that you found were not user friendly enough.

5. This has also been requested a few times and we will start to put together some starter videos and helpful tutorials but we have limited bandwidth to do so.  I was hoping that we would have more contributors by now to help with these kinds of things.

**Comment by Hassan-Ali123** [comment]
Hi! Thanks for the reply! I read your email. I now understood most of the misunderstandings or confusions about taskt, since I am new to it. Only few things I should still focus:

  1.  Some starter videos. If you think you don't have yet much bandwidth, you can provide the video samples as a package with the installer or on taskt github page: https://github.com/saucepleez/taskt
  2.  The video trainings should include all the basic commands taskt contain in it, step by step, i.e. each command should have separate video or two similar commands can include in single video or as you feel convenience.
  3.  The videos also include how to set user settings like debugger settings, output window settings (as you told me in your reply), otherwise I did not raise that as an issue.

Anyways best of luck! And thanks again for reply!
________________________________

**Comment by Hassan-Ali123** [comment]
I want to know that does taskt provide libraries as other RPA tools like UiPath Studio?

**Comment by Hassan-Ali123** [comment]
Hi! nice to see you! Few things more I want to know:

  1.  Does taskt provide any libraries for additional functionalities?
  2.  Do the updates come time by time in taskt?
  3.  Can taskt perform automation like other RPA tools like UiPath, Blue Prism, Automation Anywhere, etc.?

Please reply as soon as possible? Thanks!
________________________________

**Comment by saucepleez** [comment]
Hello,

1. What do you mean by libraries for additional functionalities?  If there is missing functionality you can create your own DLL and consume it, or create a new issue request to add functionality

2. Yes, the client is being constantly updated to add new features and functionality

3. Yes, it performs RPA like other RPA tools

**Comment by Hassan-Ali123** [comment]
By libraries I mean packages that are being installed using Package Manager, as in UiPath Studio or Visual Studio. Although we can create our own DLL, but UiPath Stuio provides built-in or custom packages to be installed if we want additional functionalities.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
