### ISSUE TITLE
Schedule task 

### ISSUE THREAD

**Issue by gowtham4gs** [saucepleez/taskt#171]
Hi saucepleez,
 i have scheduled one task but unfortunately system was locked,how can i unlock automatically and do the process when i scheduled .
Please do the needful.

Thanks

**Comment by saucepleez** [comment]
Did your task require UI to run? Anyways, you should deactivate the lock screen policy and the screen-saver policy.

**Comment by gowtham4gs** [comment]
@saucepleez thanks for reply,
 some security reasons i want sehcdule auto logoff and logon.

**Comment by saucepleez** [comment]
@gowtham4gs This application will be unable to lock and unlock the screen automatically due to lock-screen security.  You can try initializing a remote session to login to the machine and execute the script.
