### ISSUE TITLE
Password should be encrypted

### ISSUE THREAD

**Issue by jaribeiro73** [saucepleez/taskt#172]
Hi,

First of all, I would like to congratulate the people that do taskt. This is an amazing software! I have been trying to work with taskt and it does the job perfectly.

If I want to visit a website that demands login, it seems that I have to write the password in taskt and it stores in plain text. I think that this is a security issue that sould be addressed.

It is a fact, that if taskt bot has the password encrypted, and the bot is running, anybody without the password knowledge, if it accesses the PC/server that is running the bot, can wait for the bot to start, make the login with the encrypted password and then assume the control of the web page and do what he/she shouldn't be able to do.
However, if it is in plain text, he/she can read and write the username and password and later, in another place, access to web pages that they shouldn't. Encrypted password would avoid this.

So, my suggestion is to add torea checkbox to «Send keystrokes» feature that would allow to setup a keystroke as encrypted one. Of course, that when inserting the data in a website, taskt would decrypt the stored value.

**Comment by saucepleez** [comment]
Hello,

Encryption support has been added for Send Keys, Web Browser Set Text.   I have also included a command under Misc Commands for other Encryption needs.
