### ISSUE TITLE
Checkbox selection

### ISSUE THREAD

**Issue by jaribeiro73** [saucepleez/taskt#174]
I selected checkboxes using XPATH in Element Action command and ordered taskt to left click in them. Taskt finds the checkbox, however it clicks outside (right side) of checkbox. So, the checkbox is not selected.
I am using taskt 3.3.0.0.

**Comment by saucepleez** [comment]
@jaribeiro73 

You should use the 'Invoke Click' option which will check the element directly through the DOM.

If you wish to use the left click for some reason, that this command provides a X and Y adjustment if you use a manual click.  So, you would need to manually adjust it (ex. -30, -50, -100, etc.)  until you get it correct.
