### ISSUE TITLE
I cannot delete a scheduled task

### ISSUE THREAD

**Issue by jaribeiro73** [saucepleez/taskt#186]
Hi,

I cannot delete a scheduled task in task scheduler of taskt. As you can see in image below, I have the first task disabled. I want to delete it from there, because it will never be used again and it seems impossible to delete it.

![Scheduled task](https://user-images.githubusercontent.com/59137104/72270989-f88a8300-361d-11ea-8480-80d9fd8e3f11.png)

**Comment by saucepleez** [comment]
Hello,

This form is simply a wrapper around the default Windows Task Scheduler (Type 'Task Scheduler' in the start bar or (Win Key + R) > taskschd.msc.  The purpose of it was to ease the ability to schedule and execute.  You can find your jobs which will have "taskt" in the leading name.  You can then right-click and remove them.

![image](https://user-images.githubusercontent.com/5113950/72278796-c28bd580-3602-11ea-8f7c-f05550688536.png)

This wasn't developed further as it was anticipated that the web component would manage the schedules and send work to the clients.

**Comment by jaribeiro73** [comment]
Done. Thanks!
