### ISSUE TITLE
Error trying OCR

### ISSUE THREAD

**Issue by jaribeiro73** [saucepleez/taskt#187]
Hi,

I tried to read a jpg by OCR and taskt showed an error. Please, see attached image.

![Erro OCR taskt](https://user-images.githubusercontent.com/59137104/72275000-08599580-3625-11ea-8201-20b60080103d.jpg)

**Comment by saucepleez** [comment]
Last we checked, there was no open-souce OCR library. Tesseract (OCR Library) didn't produce good results so we chose to implement OneNoteOCR (https://github.com/ignatandrei/OneNoteOCR) in taskt which has a pre-requisite for OneNote to function correctly.  

I am guessing you do not have it installed in this case.  That fact was previously published but looks like it was lost when the README was updated.

We will look at adding an enhancement to detect if OCR can be initialized and populate the command accordingly.  If you need an OCR that is not OneNote, you can use a Cloud Service with REST Command (AWS, Azure, https://ocr.space/OCRAPI), obviously if you already have cloud services that will help and you should probably make note you will be sending data out from the client. There is a sample I can find for REST OCR if needed.  The other alternative is creating extensions for local (thick) proprietary software ABBYY Fine Reader, etc.

**Comment by saucepleez** [comment]
Closing due to no further response, solutions have been provided for this issue.
