### ISSUE TITLE
Unable to overwrite a variable when running in loop

### ISSUE THREAD

**Issue by varunb21** [saucepleez/taskt#188]
1. I extract text from multiple PDFs (having different data) in a loop to a variable - say PDF123
2. I use "Get Regex matches" and extract value from PDF123 --> InvoiceNo
3. I split InvoiceNo and save the final output in Invoice

Expected: 
Each time InvoiceNo and Invoice should be updated with new values as per step 2 and 3.

Actual:
InvoiceNo and Invoice retain their values from first loop and same values keep getting printed for each consecutive loop

I have tried setting the variable to blank at the end of loop but still doesn't work. 

![image](https://user-images.githubusercontent.com/47630967/72427510-e3465d80-37b1-11ea-8391-5e69ecc9ba97.png)

**Comment by saucepleez** [comment]
Hello,

Can you upload a sample task and provide some sample data to test this with? I am not clear where the issue is occuring.

**Comment by saucepleez** [comment]
Closing as no samples were provided.
