### ISSUE TITLE
12-hour time inhibits scheduling and makes timestamps ambiguous

### ISSUE THREAD

**Issue by squatmaestro** [saucepleez/taskt#190]
When displaying datetimes, Taskt sometimes uses a 12-hour format without am/pm markers.

There were 3 issues that stood out to me:

- Timestamps in the debug window are ambiguous
- The build date on the About dialog is ambiguous
- Taskt scripts can't be scheduled for 1pm or later because the Start Date and End Date boxes accept dates in 12 hour format numerals only

The cause is the use of "hh/mm/ss"-like formatting. Changing "hh" to "HH" in the three relevant locations would change to 24-hours.

I already amended my local copy of the repository.  If you'd like me to submit the fix please let me know.

Thank you for your hard work creating Taskt.

**Comment by saucepleez** [comment]
@squatmaestro  You are more than welcome to submit the PR.  Task Scheduling option was originally going to be removed as the task schedules would be managed by server component.  I suppose that entire form should get a face lift and better options management.

**Comment by saucepleez** [comment]
I am going to close this as I do not intend to spend any more time on local task scheduling -- I would prefer to focus on the server component providing this functionality.  While it is not ideal, the task schedule can be created using the existing form and then modified in the task scheduler to accommodate scheduling needs.  It will be a long process to recreate the dialogs that already exist in Windows task scheduler.
