### ISSUE TITLE
UI Automation Fails for Datagrid

### ISSUE THREAD

**Issue by shreyas2487** [saucepleez/taskt#192]
While using UI Automation - Get Value From Element on a data grid, none of the parameter returns value as the actual data of either row or cell. Instead 'Name' parameter returns value in 'columnname rownumber' format.
What can be done to get the table/row/cell value in parameters, or table/row/cell object within the code?

**Comment by saucepleez** [comment]
@shreyas2487 Can you give a scenario where this can be tested?  What kind of application are you automating and what kind of DataGrid is it?

**Comment by shreyas2487** [comment]
It is a simple windows application where the datagrid is being populated at runtime.

**Comment by saucepleez** [comment]
Closing this for now, I do not believe complex controls are supported.  If support is still needed, please open a new issue.
