### ISSUE TITLE
Execute query in taskt

### ISSUE THREAD

**Issue by Dmajensen** [saucepleez/taskt#202]
How do I execute a query in Taskt? 

I have set up a datebase connection and then I`m using the command: Execute database query. I insert the instance name, then write this query: 

SELECT CONVERT(VARCHAR(2), GETDATE(), 4) AS [DD]

I want to return the dataset and apply it to the variable {[DD]}, and to check the result I show the input of the variable in a message, but the output is just {[DD]}. 
what am I missing?

**Comment by Dmajensen** [comment]
I succeded to get the result of the query in my variable. 

A new issue is, when I execute this query: 
SELECT institutionskode, tjenestenummer, beløb, lønart, DATEPART(MM, DATEADD(month,-1, GETDATE()) )as Bogføringsmåned, DATEPART(YY, dateadd(month, -1, Getdate())) as Bogføringsår 
FROM tblFleksloenrefusionBogfoeringtestDB

I only get 1 row in my variable, but there are 100 rows in the datatable. 
How do I get all 100 rows?

**Comment by saucepleez** [comment]
Closing due to no response
