### ISSUE TITLE
Newbie  Can't find Input Commands that are on the wiki

### ISSUE THREAD

**Issue by dkgest** [saucepleez/taskt#203]
The Wiki lists Input as having an element called Click UI Item but my actual taskt executable does not list that under Input.   I am trying to put a userid in a fat client input field and move to another input field and put in a password.   I have been using Blueprism for several months so have some familiarity with the concepts but not with taskt.   Thank you for any help you can give with driving a Windows interface - our core banking software.

**Comment by monica1975** [comment]
I'm just starting to use Taskt and i have the same problem.

**Comment by saucepleez** [comment]
Hello,

The Click UI Item was replaced completely by **Input Commands > UI Automation**.  The UI Automation command enables "recording" to capture elements. The GitHub Wiki associated with this project is out of date.  https://wiki.taskt.net/ is the current Wiki, but the actual Wiki docs need to be regenerated and updated.

Please note there are some script samples located at:
https://github.com/saucepleez/taskt/tree/development-branch/taskt/Sample%20Scripts

Specifically there is a UI Automation sample:
https://github.com/saucepleez/taskt/blob/development-branch/taskt/Sample%20Scripts/2.x%20Use%20Case%20Samples/Thick%20App%20Automation%20Sample%20%5B2.1.0.0%5D.xml
