### ISSUE TITLE
The value of the variable is not being passed as a parameter in a web element action

### ISSUE THREAD

**Issue by rodrigoaraujos** [saucepleez/taskt#205]
I have a task where, when taking the value of a cell in excel, in this case ‘A1’:

![image](https://user-images.githubusercontent.com/38005146/78511673-1a0a8f00-7775-11ea-91fe-228db69f0e0b.png)

I need to select this in a select option of a website:

![image](https://user-images.githubusercontent.com/38005146/78511693-3e666b80-7775-11ea-8ef2-f1bcd63803ea.png)

Then I perform the following actions:
    - ExcelCreateApplicationCommand
    - ExcelOpenWorkbookCommand
    - ExcelGetLastRowCommand
    - BeginNumberOfTimesLoopCommand
    - ExcelGetCellCommand 
Saving the cell value in the variable vColA.

When I try to assign the value of the variable vColA as an attribute of an action in the browser, as shown below, this value is not recognized and then an error occurs in the execution:

![image](https://user-images.githubusercontent.com/38005146/78511780-9a30f480-7775-11ea-997e-bc2c44f194aa.png)

![image](https://user-images.githubusercontent.com/38005146/78511848-2a6f3980-7776-11ea-93c2-4b7516ba90ec.png)

But when I input the value directly, without using the variable, the execution normally occurs:

![image](https://user-images.githubusercontent.com/38005146/78511793-ba60b380-7775-11ea-999b-1a256ccb7032.png)

![image](https://user-images.githubusercontent.com/38005146/78511840-13304c00-7776-11ea-951d-4220192dd6c2.png)

**Comment by saucepleez** [comment]
Thank you for reporting this issue. I was able to reproduce it and fix the issue.  This will be fixed in the next release, alternatively, you can build from the develop branch to check out the fix if you would like.

**Comment by rodrigoaraujos** [comment]
@saucepleez thanks for answering!
