### ISSUE TITLE
Error in Automation

### ISSUE THREAD

**Issue by monica1975** [saucepleez/taskt#207]
Hello.
I'm trying to use the Ui automation in order to  check if a windows is asking to save a file. Every time i start recording  and i click the "Do you want to save this file" windows i get an error:
Error in r
![Capturar](https://user-images.githubusercontent.com/63428074/79888552-c21a8c00-83f4-11ea-9fe6-65ca17e646ed.JPG)
ecording, please try again.
system.Runtime.InteropServices.COMExcption (0x8001010D).....
![image](https://user-images.githubusercontent.com/63428074/79888453-9ac3bf00-83f4-11ea-9cf5-b53f8dde465f.png)

Can you help? Am i doing something wrong?

**Comment by monica1975** [comment]
One more information: i'm using powerbi desktop application.

**Comment by saucepleez** [comment]
Is it possible to use send keys instead? You can send CTRL+S.  You can also use the `Send Advanced Keystrokes` command.

**Comment by saucepleez** [comment]
I have added a new command `Send Hotkey` which will enable you to simply send a hotkey to the window to save.

![image](https://user-images.githubusercontent.com/5113950/83828151-ffd62a00-a6ad-11ea-9dcd-507694e59752.png)
