### ISSUE TITLE
I can't get my version of your notepad tutorial program to work

### ISSUE THREAD

**Issue by KaiALindgren** [saucepleez/taskt#208]
Could it be that I have wrong Taskt version?

I can't easily copy my version of the program so I at first make only this short question.
Hope you have time to my question.

Regards,

Kai Lindgren
kai.a.lindgren@outlook.com
Tel. +358 50 441 6364
Finland

**Comment by saucepleez** [comment]
Can you attach a copy of the sample you are having trouble with?

**Comment by KaiALindgren** [comment]
Nice to get your reply saucepleez, thanks!
I am making some material of Taskt to my students. I have found  some nice working robots, but also some which I can’t use. I had problems at least in these robots and commands:

C:\RPA_Taskt\taskt-3.4.0.0\taskt\Sample Scripts\Calculator UI Automation Sample.xml.
Command: Send Outlook Email.

Sincerely yours,

Kai Lindgren
Muorinpiha 7
02400 Kirkkonummi
Finland
Tel: +358 50 441 6364

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
