### ISSUE TITLE
Newbie - How to read specific text from .txt file

### ISSUE THREAD

**Issue by Iron-Hunter** [saucepleez/taskt#209]
Hello, I am fairly new to RPA overall and can't seem to be able to extract text from a .txt file. I can open the file needed without issues I just want to extract specific text and preferably paste it in a new notepad instance.

Thanks in advance

**Comment by saucepleez** [comment]
When you say specific text, can you please give a scenario?  There are multiple methods currently to do this in taskt. 

You should review the `Data Commands` group, specifically the `Split Text`, `Substring`, and `Text Extraction` Command.

**Comment by Iron-Hunter** [comment]
Thank you, I have taken a smarter approach and downloaded all examples and am studying each one. I believe I have found a solution to my question by doing so. Thank you
