### ISSUE TITLE
issue when creating the scheduler task and press from "disable" to "enable". An null reference occurs

### ISSUE THREAD

**Issue by arctocore** [saucepleez/taskt#21]
issue when creating the scheduler task and press from "disable" to "enable". An null reference occurs

**Comment by saucepleez** [comment]
Thank you. I have confirmed this bug and I am working on a resolution.

**Comment by saucepleez** [comment]
This has been published to the development branch if you would like to test it out further. I am planning on merging into master and releasing this as a part of an official update on 9/27.
