### ISSUE TITLE
Need a default ping command to check status of server 

### ISSUE THREAD

**Issue by kanchandebnath** [saucepleez/taskt#215]
If we can have a default ping command to check server/machine status  would be helpful

**Comment by naga1992** [comment]
added ping command , you can find it under misc ommands ping command

**Comment by saucepleez** [comment]
Thanks @naga1992 I have enhanced the command and provided samples.

**Comment by naga1992** [comment]
Cool thanks @saucepleez

**Comment by kanchandebnath** [comment]
@naga1992 @saucepleez   Thank  you for providing the   Ping command so promptly
