### ISSUE TITLE
file Extraction

### ISSUE THREAD

**Issue by kevin89172** [saucepleez/taskt#219]
If  file have password file Extraction No field to enter password 
so file Extraction commands will not working
can add file password field ?thanks

**Comment by saucepleez** [comment]
File Extraction -- What kind of file are you extracting? I assume this is ZIP file extraction and you want to be able to provide for a password?

**Comment by VeraHung** [comment]
Yes, I want this function. Thanks.

**Comment by saucepleez** [comment]
I have added this functionality in DEV.  It will be available in the next release.
