### ISSUE TITLE
DateTime difference

### ISSUE THREAD

**Issue by MukeshMikky** [saucepleez/taskt#226]
Hi, Anyone please let me know how we can find difference between two dates in taskt? Thanks!

**Comment by naga1992** [comment]
Hi @MukeshMikky  you can try using Date Calculation command , which is present in the Data commands section , there is a sample script in the below link 
https://raw.githubusercontent.com/saucepleez/taskt/development-branch/taskt/Sample%20Scripts/Date%20Calculation%20Sample.xml

**Comment by MukeshMikky** [comment]
Hi @naga1992, This helps in adding a number to date. What I need is to find the number of days between two dates. Thanks.

**Comment by MukeshMikky** [comment]
Hi @naga1992 I was able to add the Date Difference logic in Taskt, We are good to close this.
