### ISSUE TITLE
the need of a system variable that only show shortdatestring

### ISSUE THREAD

**Issue by arctocore** [saucepleez/taskt#23]
the need of a system variable that only show shortdatestring instead og adding time at the end.
Many web systems only need the short date string. And it is a hell to manupilate Datime.Now and remove the last time digits.

**Comment by saucepleez** [comment]
This was brought to attention previously.  Please see the new functionality for Date Calculation under Variable Commands.  It lets you define a specific format like "MM/dd/yyyy".  There is also a sample task for date calculations.  You will need to specify one of the list items (Add Days and 0) then simply specify the format.  As an enhancement, we will look at adding a Format command for values.

**Comment by saucepleez** [comment]
This has been published to the development branch if you would like to test it out further. I am planning on merging into master and releasing this as a part of an official update on 9/27.

You can see the format specifiers here:

https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings?view=netframework-4.7.2
