### ISSUE TITLE
running throw error on WebSocketClient.cs

### ISSUE THREAD

**Issue by mondemonde** [saucepleez/taskt#232]
Whenever i run the script ,I get this error...

![image](https://user-images.githubusercontent.com/18346619/90256856-e8b77380-de78-11ea-89c0-cf1a42746c70.png)

websocket is null.

So in order to continue I just  bypass it ,
![image](https://user-images.githubusercontent.com/18346619/90258425-23221000-de7b-11ea-8f07-f2aa1b0caf59.png)

What is this websocket for? is this for  the taskt server workforce?

![image](https://user-images.githubusercontent.com/18346619/90258774-96c41d00-de7b-11ea-84b1-578f1ba6f68a.png)
 
but I do not have it.

Obviously I'm just new here.

Thanks.

**Comment by billxiao** [comment]
I got the same exception.

**Comment by AnuradhaOpenRPA** [comment]
I too got the same exception.

**Comment by saucepleez** [comment]
Hello, this should be resolved, there is now a null check for the web socket connection.  Not sure why this cropped up suddenly?
