### ISSUE TITLE
Send Keystrokes clearing brackets in text

### ISSUE THREAD

**Issue by RedRenar** [saucepleez/taskt#234]
Hello!
This is the code:
{"$type":"taskt.Core.Automation.Commands.SendKeysCommand, taskt","v_WindowName":"Current Window"**,"v_TextToSend":"filename(1).doc"**,"v_EncryptionOption":"Not Encrypted","CommandID":"acc4e1e4-3b9d-4802-bffd-b85a829221e1","CommandName":"SendKeysCommand","IsCommented":false,"SelectionName":"Send Keystrokes","DefaultPause":0,"LineNumber":0,"PauseBeforeExeucution":false,"DisplayForeColor":"SteelBlue","v_Comment":"Вставить имя файла","CommandEnabled":true,"CustomRendering":true}
Here we can see that text to send is "filename(1).doc"

but  the overall result is "filename1.doc" . 

Please fix it

**Comment by saucepleez** [comment]
That is the expected outcome.  Please open a new issue and further elaborate on what issue you are experiencing.
