### ISSUE TITLE
"Timeout (Seconds)" parameter for Web Browser Commands - Execute Script

### ISSUE THREAD

**Issue by AlanGould** [saucepleez/taskt#240]
I'm a big fan of Taskt, thanks for the project :)

The default timeout for Web Browser Commands - Execute Script is 60 seconds, however I have scripts that often run beyond 60 seconds, which therefore cause an error (i.e. waiting for the web server to return a result or initiate a download).  Unfortunately I have no control over these third party servers and how long they take to respond.

Is it possible to override this default 60 second timeout?  If not, I'd like to submit this as a feature request!

**Comment by saucepleez** [comment]
Hello,

Thanks for opening an issue!  I have added this feature, are you able to test it from the development branch?

![image](https://user-images.githubusercontent.com/5113950/101235001-73271b80-3692-11eb-8985-89a1a8a26824.png)

If this resolves your issue, you may go ahead and close this request, thanks.

**Comment by AlanGould** [comment]
Ah great, thanks for adding this feature!  I'll run the dev branch for a week and let you know know if this does not solve the issue.
