### ISSUE TITLE
New Sheet in Excel?

### ISSUE THREAD

**Issue by ausckirk** [saucepleez/taskt#241]
It is possible to create a new Sheet within an Excel workbook with taskt?  There is an easy way to "Activate Sheet" and to "Add  Workbook" which both operate as expected,  but I have not been able to add a Sheet within an existing workbook.

Thanks in advance.

**Comment by saucepleez** [comment]
Hi, I will look at adding a command specifically for this.  Currently, you can use the Advanced Keystrokes command to send the hotkey to replicate the action.  

[Add Excel Sheet.xml.txt](https://github.com/saucepleez/taskt/files/5646520/Add.Excel.Sheet.xml.txt)
