### ISSUE TITLE
Run Macro command

### ISSUE THREAD

**Issue by ShahinHassan025** [saucepleez/taskt#246]
I want to run macro command i m inserting macro name but its not working pls help me out .

**Comment by AntonYakimov** [comment]
Any update. I'm aslo interested.

**Comment by saucepleez** [comment]
You can use the Excel Commands to open an existing workbook, and then call the macro command:

![image](https://user-images.githubusercontent.com/5113950/127729504-92d9cffb-4718-4ffe-9688-cbd05f4f79ad.png)

You will want to preface the macro name with the context like `ThisWorkbook.MacroName`
