### ISSUE TITLE
Internet Explorer on Win 10

### ISSUE THREAD

**Issue by onvickirk** [saucepleez/taskt#247]
Hey,

Having an issue with the IE Browser Engine Type on the "Web Browser Command - Create Browser' on Win10 boxes.   IE will launch, and navigate to the first URL, but after that further commands, like navigate to new URL, will timeout.  This works fine on my Win7 box (IE version 11.0.9600.19596 ) but on two different win10 boxes ( IE version 11.789.19041.0 ), the selenium timeouts occur.  I tried pulling in the latest IEDriverServer.exe but no change.    Chrome works fine.  

Any ideas?

P.S. And FYI, on both Win7 and Win10,  the commands under the "IE Browser Commands", the ones utilizing the Interop mechanism, work fine.

**Comment by saucepleez** [comment]
You should attempt a different web driver version from selenium which goes in the Resources folder from the root project.
