### ISSUE TITLE
[Enhancement] Allow New Variable name to be pulled from variable itself

### ISSUE THREAD

**Issue by ITE-Sound** [saucepleez/taskt#254]
This allows for dynamic variable creation.  For example, in my case, i am making a variable out of columns returned from a db query.  the name of the variable is the column name and the value is the value.

I accomplished this edit by merely adding ;
     var scriptPath = v_ScriptPath.ConvertToUserVariable(sender);     var scriptPath = v_ScriptPath.ConvertToUserVariable(sender);

to the runcommand proc in RunScriptCommand.cs

**Comment by saucepleez** [comment]
You can now use the set variable command which can convert variables within the input text.
