### ISSUE TITLE
[New Functionality]  Run Powershell Script 

### ISSUE THREAD

**Issue by ITE-Sound** [saucepleez/taskt#255]
I would like to able to supply a script either by filename or by a string variable.
-The script/script text should be updated with variable values where a context variable is represented in the text with some unique string before runtime. ex    <<Date.Now>> replaced by the value of the taskt variable {Date.Now}

- If the return of the script json with variableName and values, then these variables should be added to the engine context for use further down the line.

**Comment by saucepleez** [comment]
Hello,

Powershell command has been added with this functionality.
