### ISSUE TITLE
After append Image,append text will replace the image,Help me.

### ISSUE THREAD

**Issue by 22668923** [saucepleez/taskt#256]
In this program ,I operate the word.  at first   append text,then append image,at last append text. but the last text replace the image.

**Comment by nguyenminhduc110392** [comment]
![image_2021_04_26T10_34_25_983Z](https://user-images.githubusercontent.com/47959201/116069563-b754a000-a6b5-11eb-8b22-11cda673773a.png)

Hope it can help
