### ISSUE TITLE
Add find element by CSS selector to Element action Web automation 

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#26]
Hi, it will be great if you can add find by CSS warinat to Element action filter. 
In selenium i'll take this command: .FindElementByCssSelector("")
Thanks!

**Comment by saucepleez** [comment]
@msshubin You can add CSS selectors into the 'Element Search Parameter' box such as **input#header-search-bar**

**Comment by atotalnoob** [comment]
Does this support all css selectors? Ie, >, +, chained selectors? 

What happens if it returns multiple elements?

**Comment by msshubin** [comment]
Selenium have two commands: FindElement and FindElements. Maybe Taskt return first?

**Comment by msshubin** [comment]
> @msshubin You can add CSS selectors into the 'Element Search Parameter' box such as **input#header-search-bar**
> 
> dev branch has been updated with the changes if you want to test it out or review.

shure, i'll test it. Thanks!

**Comment by atotalnoob** [comment]
You should be able to iterate over a collection of elements. I could see it being beneficial.

**Comment by msshubin** [comment]
> dev branch has been updated with the changes if you want to test it out or review.
I'll review and test it. All works great! Thanks for your amazing product.

**Comment by saucepleez** [comment]
@msshubin @atotalnoob 

FindElementByCssSelector finds the first element matching the specified CSS selector. 

There are methods that can potentially return multiple elements -- at that point it begins getting complex and I would suspect that we would need some type of "helper" form that executes the selenium and shows you the potential options that would be returned....

For example:

1) Select Selenium Search Method (Ex. FindElementsByCSSSelector)
2) Specify the search string (Ex. input#header-search-bar)
3) User Clicks "Test Configuration" Button
4) Selenium Executes and Returns Array of WebElements, Presented to Bot Developer
5) Bot Developer can view the properties of each item and select whichever element is the one they want.

Without writing a Chrome extension or running Selenium once, it is not possible to know what potential elements are on the page.
