### ISSUE TITLE
[bug] Send Keystrokes - leading 0 of numeric string is ignored 

### ISSUE THREAD

**Issue by ghost** [saucepleez/taskt#269]
I set numeric string started with 0(e.g. 000001) to Insert Variable of Send Keystrokes. 
But Send Keystrokes send string without leading 0.

![image](https://user-images.githubusercontent.com/20365376/127735540-e9ad896e-7fea-4e4b-9382-1b71f38d6121.png)

If string conatins nonnumeric characters(e.g. 000001a), Send Keystrokes works fine.

**Comment by rcktrncn** [comment]
Please insert "Set Engine Preference" before Send Keystrokes.
"Set Engine Preference" is "Disable Automatic Calculations"
