### ISSUE TITLE
Resume Selenium Option

### ISSUE THREAD

**Issue by saucepleez** [saucepleez/taskt#28]
taskt should provide the option to resume control of an existing Selenium instance from a new script.  Selenium Name -> Instance ID should be tracked instead of the actual Selenium Object.

Identified by @msshubin

**Comment by msshubin** [comment]
All RemoteWebDriver instances have SessionID, but can't be change and only have get setter. It will be great do this things in selenium project, mybe additional driver constructor, that receive on enter sessionID of already started browser instance.

**Comment by saucepleez** [comment]
@msshubin taskt tracks applications during runtime which associates an instance name to an application class (such as Excel or SeleniumDriver).  We can start tracking those instances "globally" instead which would let you access them between script executions, assuming you never disposed of the session.

**Comment by msshubin** [comment]
All right. That is why now i need continuous loop for do this - i start teskt, open browser and then wait signals from external application. Just now - it just text files ) I'll checkout current dev-branch and test all features.

**Comment by saucepleez** [comment]
@msshubin 

Sure. Continous Loop has been added to the dev branch so you can check that out.  I have added instance tracking between script executions, however, it will only work if the application is not closed.

Selenium does not officially support attaching to existing instances as indicated [here](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/18).  I attempted to implement the RemoteDriver workaround you previously mentioned as well as a few other workarounds (serializing, etc), but it did not work correctly/as intended.
