### ISSUE TITLE
Possibility to add task command to any position in sequence

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#31]
Example. A have sequence of commands. Then, i need to add some commands to the middle of my sequence. I add it consequentially and then move it by mouse to exact positions. Maybe we can analize current cursor position in sequence at right and add new command after it? Or maybe there are drag&drop function from left to right?

**Comment by saucepleez** [comment]
So in summary, when you add a command, you would expect the command to be added below the currently selected command in the list?

**Comment by saucepleez** [comment]
I have added the functionality to insert commands at either the end of the script or inline, below the last selected command.  This will be an option you can check from Settings:

![image](https://user-images.githubusercontent.com/5113950/46386539-0833c180-c690-11e8-84d2-0cfefe2457d4.png)

This is now pushed to the dev branch if you want to check it out.

**Comment by msshubin** [comment]
@saucepleez thanks. After some testing it seems to strage behavior. When i add one command to command list - all ok - it adding to exact position. But if i add pair command such as if-else or loop-end - then start command placed to exact position but end position added to the end of all commands. What you think about it?

**Comment by saucepleez** [comment]
Sure, I will reopen.

**Comment by saucepleez** [comment]
I have pushed the changes to the dev branch -- the insertion preference now includes and handles loops/if statements.
