### ISSUE TITLE
Restructure Command Checks

### ISSUE THREAD

**Issue by saucepleez** [saucepleez/taskt#32]
Instead of consistently checking if the parentCommand matches a type

`  if ((parentCommand is Core.AutomationCommands.BeginNumberOfTimesLoopCommand) || (parentCommand is Core.AutomationCommands.BeginContinousLoopCommand) || (parentCommand is Core.AutomationCommands.BeginListLoopCommand) || (parentCommand is Core.AutomationCommands.BeginIfCommand) || parentCommand is Core.AutomationCommands.BeginExcelDatasetLoopCommand)`

Create an Extension Method or some other way to easily check:

`Command.IsType(Loop)` or `parentCommand is LoopCommand`

**Comment by vadim1996wolf** [comment]
To realize above described you should refactor AutomationCommands.cs:
extract each group of commands,
inherit from script : new class group, from group: command
check if command is an instance of group then perform some action.

**Comment by vadim1996wolf** [comment]
To realize above described i would recommend to refactor AutomationCommands.cs:
- extract each group of commands,
- inherit from scriptCommand : new class scriptGroup, from group: someCommand
- check if command is an instance of group then perform some action.

For too continuous code lines coders usually use transitions to new lines. As an example:
![image](https://user-images.githubusercontent.com/13113616/52795214-659a3f00-3082-11e9-98bc-aea81415045c.png)

**Comment by saucepleez** [comment]
@vadim1996wolf 

Agreed,  Automation Commands in DEV have been refactored into individual files. We should probably look at implementing additional interfaces for certain types.
