### ISSUE TITLE
Add GUI element exists on if Command types

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#34]
@saucepleez it is a great idea - to have option **Web Element Exists** in types of **If Command** and it will be great to have same type for GUI applications.

**Comment by saucepleez** [comment]
There is one for WebElements in **If Command**:

![image](https://user-images.githubusercontent.com/5113950/46441695-5353e000-c735-11e8-94fd-41ec6c08fcf0.png)

**Comment by msshubin** [comment]
Yes, for Web command all ok. Can you develop same feature for GUI applications? **GUI element exists**?
