### ISSUE TITLE
Error in new script in first command

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#36]
Hi @saucepleez . I Create new script, then double click to command **Text Extraction**, then add follow:
![image](https://user-images.githubusercontent.com/22539710/46455227-13cfd700-c7bb-11e8-9ffe-b99431c69073.png)
after click **OK** i have:
![2018-10-04_09-50-34](https://user-images.githubusercontent.com/22539710/46455246-32ce6900-c7bb-11e8-90ee-7ff9f2be709c.png)
Full text error in this window:
[FullErrorText.txt](https://github.com/saucepleez/taskt/files/2445041/FullErrorText.txt)

If i click Continue - all ok and i can do what i need. If then i double click to this existing command and click again **Ok** - there are no error.

**Comment by saucepleez** [comment]
Please try the latest in dev branch to see if it helps.  The issue appears to occur when an item is being added and formatted to the listview.
