### ISSUE TITLE
Add feature for copy-paste many actions and feature to cut-paste many actions

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#37]
@saucepleez hi. On context menu on rigth mouse button we have **Copy Selected Action**, but it will be great to have **Copy Selected Actions** and **Cut Selected Actions**

**Comment by saucepleez** [comment]
@msshubin 

Thank you. I have updated the dev branch to reflect these changes.

**Comment by msshubin** [comment]
@saucepleez it's amaizing! Big thanks! Worked perfect!
