### ISSUE TITLE
Feature for using variable values in Comment commands

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#38]
@saucepleez . For track and support scripts it will be great if i can add variable values into the **Add Come Comment** like this:
![image](https://user-images.githubusercontent.com/22539710/46475762-7c3ca980-c7f7-11e8-991f-a13419893856.png)

**Comment by msshubin** [comment]
Sorry, i inaccurately expressed. When we start script many times and it handles with different values of variables, i like to know then in logs what values pass the script... That is why i'll try to save it to Add Comment. Can you advice me how and where i can save exact values from each start of script?

**Comment by saucepleez** [comment]
Ok, I understand.  We can add a setting when the engine starts to process Comments at run-time so it will log the actual value of the variables within comments and write to log files.  We could also add a new command to enable logging from the script.

In the meantime, you could use **Text File Commands > Write to File** and specify the text to be written as something like:

[DateTime.Now] - Desktop Path Variable: [Folder.Desktop]

**Comment by saucepleez** [comment]
Comment Commands will process variables during execution now and you can now use **Data Commands > Log Data** to log specifically to the engine instance or a custom log file.
