### ISSUE TITLE
Possibility to insert variable to Click UI Item window

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#39]
@saucepleez sometimes GUI applications have dynamic window name and when i add command **Click UI Item** i must choose or enter exactly window name. It will be nice, if i can select **CurrentWindow** and **Insert variable** for window name.

**Comment by saucepleez** [comment]
Ok, will be reviewed.

**Comment by saucepleez** [comment]
This has been updated to the dev branch, thanks.
