### ISSUE TITLE
Posibility to find and iteract GUI element by class, type and other

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#40]
Recently i using [https://github.com/Roemer/FlaUI] to automate GUI applications, there we can specify some criteries to find GUI elements. For example, i have applications witch elements have the same names and different ControlType...

Other side - using [https://github.com/2gis/Winium.Desktop] - they try to do all automation by selenium style.
Look here:
![image](https://user-images.githubusercontent.com/22539710/46483784-810a5900-c809-11e8-8ace-7c0b104ffcf9.png)
And here:
![image](https://user-images.githubusercontent.com/22539710/46483835-9e3f2780-c809-11e8-9c3e-aba57a4c962d.png)

I'll say right away, that i can't work with AutomationID becose it is changing after each start of application.

**Comment by saucepleez** [comment]
@msshubin 

This is affecting the **Get UI Item** command. I would say we can remove the requirement for acquiring the Automation ID at design time.  Instead, the Automation ID will be acquired by the automation engine at run-time based on the Element name.  This will alleviate your current issue as the Automation ID is transparent and irrelevant assuming you get the Element name correct during design time.

More broadly speaking, there needs to be some type of "Advanced GUI" builder which lets you select an item by multiple window attributes (handle name, class name, etc).  There should also be some type of 'Click to Record' feature which watches the window being clicked and loads the potential properties from the handle receiving the click.  I would suggest that should be a new issue item and that is probably going to take some time to build as it may require migrating to a new UI Automation Library (currently is uses Windows UI Automation framework).

**Comment by saucepleez** [comment]
@msshubin 

Please see latest dev branch for 'UI Automation' Command.
