### ISSUE TITLE
Add String.Replace() command

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#43]
@saucepleez it will be great idea, if we can use String.Replace() command near TaskT scripts. How you think?

**Comment by saucepleez** [comment]
@msshubin This was just added in the dev branch

**Comment by msshubin** [comment]
Works great. Thanks @saucepleez.

**Comment by msshubin** [comment]
@saucepleez I try to replace + to {+} becose i need then sendkeyboard to Gui Application. I'll try, but have an error:
```
2018-10-08 18:52:17.161 +03:00 [INF] Error: System.Exception: System.ArgumentException: Строка не может иметь нулевую длину.
Имя параметра: oldValue
   в System.String.ReplaceInternal(String oldValue, String newValue)
   в System.String.Replace(String oldValue, String newValue)
   в taskt.Core.AutomationCommands.StringReplaceCommand.RunCommand(Object sender) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 3774
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 210
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 237
   в taskt.Core.AutomationEngineInstance.ExecuteScript(String filePath) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 108
```
![image](https://user-images.githubusercontent.com/22539710/46619948-7404a700-cb34-11e8-8b43-82b2a2f07e34.png)

**Comment by saucepleez** [comment]
@msshubin 

Are you sure that **Phone** has value?

**Comment by saucepleez** [comment]
I have confirmed this bug -- it is occuring because under the hood, you can perform math on variables, so for example you can say [v1] + [v2] and get a result assuming the two are mathematically possible.  The issue here is the + sign is being executed as math and returns a null.

**Comment by msshubin** [comment]
![image](https://user-images.githubusercontent.com/22539710/46620497-f477d780-cb35-11e8-9f4a-aaf8186b68e2.png)

ok. How i can resolve it?
