### ISSUE TITLE
More useful error handling

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#44]
@saucepleez  at current version we have only two ways if error is thrown in command:
continue or stop. Can you modify it like try catch finally in c#. I mean if error is thrown, then i can do some commands or if it ok - then some commans. Maybe it could be added to types for command **If** an addition to other... Like this:
1. Error Handling [Action: Continue Processing]
2. Activate Window [Target Window: Skype]
3.     If Error thrown
4.          // Comment: Items in this section will run if the statement is true
5.          Show Message [Message: There is now window opened like Skype]
6.     Else
7.          Show Message [Message: All ok, i'll activate window]
8.     End If

Error Handling may save Exception string to variable )

**Comment by saucepleez** [comment]
Agreed, there need to be a more verbose way to take actions once an error occurs.

**Comment by saucepleez** [comment]
I have added the **Error Occured** type to If Commands.  You can see the sample script from the repo.
