### ISSUE TITLE
Format Data stopped working

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#49]
@saucepleez till some commits, command Format Data broken. I have simple script, that early worked fine.
[birthDate.xml.txt](https://github.com/saucepleez/taskt/files/2459476/birthDate.xml.txt)

Early i have result 22.11.1982

![image](https://user-images.githubusercontent.com/22539710/46656036-2765ae00-cbbe-11e8-9caf-e68d41ad160e.png)

**Comment by saucepleez** [comment]
Not sure what happened here, the code for the command does not store the variable properly.  Fixed,

**Comment by saucepleez** [comment]
Released new Binary

https://github.com/saucepleez/taskt/releases/tag/v1.9.3.0
