### ISSUE TITLE
Returning an according text by number or added to one string

### ISSUE THREAD

**Issue by andreyofficinal** [saucepleez/taskt#57]
Found a malfunction:
every command, I am trying to get the data, returns the first according value, but not the others.
Examples:
I try **Element Action** to get text from field found by CSS Selector. I use some selector that will find a lot of fields(as _"div.parametrs .registerBox"_ where registerBox is a class of more than one element on page), but all I got is contents of the first .registerBox element and... that's all.
Okay, I set the selector to get the parent element text(_"div.parametrs"_) and get string, containing my information. But when I am trying to use the **RegEx Extraction** to get exactly those strings that I need at last, it gives me the good result in first iteration(I increase the **Select Matching Group Index** attribute in every loop) and empty in the others.
Please could you help me - show the working regex string or repair that bug?

**Comment by saucepleez** [comment]
Can you please supply sample variable value and the regex match being used?

**Comment by andreyofficinal** [comment]
Attached files into this message: (containing worked file and test example), added some debug info.
Additionally tested on microsoft site.
The text is
> In This Article
> Definition
> Examples
> Remarks
> Methods
> Applies to

The regex is
> ^([\w-]+)

 taken from https://github.com/saucepleez/taskt-wiki/blob/master/automation-commands/data-commands/regex-extraction-command.md.
Also doesn't work regex like
> [^\n-]+

and really needed regex is
> [^\n]+\n[^\n]+\nНачальная цена\n[^\n]+\n[^\n]+\n[^\n]+\nЗаказчик:\n[^\n]+\n[^\n]+\n([^\n]+\n[^\n]+\n)?Размещено: [^\n]+\nОбновлено: [^\n]+

All written regex tested on https://regex101.com/.

Could you also join results from **Element Action** into one string or add this option?

[2.zip](https://github.com/saucepleez/taskt/files/2497977/2.zip)

**Comment by saucepleez** [comment]
Regarding multiple elements, I have added the ability to loop multiple elements now in latest dev branch and included a sample script.  Are you building from source or are you using released binary?

I will investigate the regex issue as well shortly.

**Comment by saucepleez** [comment]
Ok so after reviewing, this is how the string looks:

    "In This Article\r\nDefinition\r\nExamples\r\nRemarks\r\nMethods\r\nApplies to"

The RegEx being used isn't accounting for that format.  But you should not need to use RegEx at all, you can use the Split String Command, see attached sample.

[Git Issue 57 - Parsing Strings.zip](https://github.com/saucepleez/taskt/files/2498478/Git.Issue.57.-.Parsing.Strings.zip)

This issue should also be resolved with the additional ability to loop multiple selenium elements.

**Comment by andreyofficinal** [comment]
@saucepleez Thank you!
