### ISSUE TITLE
Error in Find element by CSS or XPath Click action

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#65]
Hi @saucepleez, i'll run my script in new version from devbranch and have a error which was not there before.
``
2018-10-22 09:53:31.189 +03:00 [INF] Running Line 7: Element Action [Find Element By XPath and Left Click, Instance Name: 'default']
2018-10-22 09:53:31.417 +03:00 [INF] Result Code: Error
2018-10-22 09:53:32.220 +03:00 [INF] Error: System.Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Не удается неявно преобразовать тип "int" в "string"
   в CallSite.Target(Closure , CallSite , Object )
   в taskt.Core.AutomationCommands.SeleniumBrowserElementActionCommand.RunCommand(Object sender) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 1092
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 212
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 233
   в taskt.Core.AutomationEngineInstance.ExecuteScript(String filePath) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 110
``

**Comment by msshubin** [comment]
I'll rollback to taskt v.1.9.3.0 and here all ok.

**Comment by saucepleez** [comment]
@msshubin 

This is occuring because I changed the mouse move command for X and Y position to use a string instead of implicitly requiring an int.  This is so that you can use variables with the command.  I have updated the offending code, please check latest from DEV.
