### ISSUE TITLE
Indexed working elements and lists

### ISSUE THREAD

**Issue by andreyofficinal** [saucepleez/taskt#66]
Hello. Could you add a variable support for fields **Element Search Parameter** in **Element Action**? To access those elements depending on variables set before?
And is there any way to get the list content outside of **Loop List** command? Can I take the value by index?

**Comment by msshubin** [comment]
@saucepleez it's amazing feature. Now i can export JSON variables after script work for other applications. Can you advice me simple way to submit to the entrance variable values? May i have input file with JSON and simply load it to context?

Example. 
1. I have file InputVars.json
2. External application make JSON string in this file with initial values of variables
3. TaskT script starts and load this file and initialize variables values
4. Script works....
5. At the end of script i'll write JSON variables to file OutPutVars.json
6. External application can handle it and do some things

**Comment by saucepleez** [comment]
@msshubin 

Yes, you can save following into json file:

     {
      "Var1": "Hello!"
     }

Use Read Text File to read data and apply to variable (ex {vParams}).

You can now call variable like `{vParams}` which will give full json string or use a selector `{vParams => $.Var1}` to get the value "Hello!" for example

**Comment by andreyofficinal** [comment]
@saucepleez Tnahk you!

**Comment by msshubin** [comment]
@saucepleez sorry again, but in last dev-build your examples: Advanced Variable Processing Sample.xml
works strange:
![2018-10-26_18-06-11](https://user-images.githubusercontent.com/22539710/47571614-0b963200-d94a-11e8-9eb1-ed2ab7a06101.png)
![2018-10-26_18-06-24](https://user-images.githubusercontent.com/22539710/47571617-0d5ff580-d94a-11e8-83d2-c9ad4529bc56.png)

**Comment by msshubin** [comment]
i was expecting values

**Comment by saucepleez** [comment]
@msshubin You need to change variable marker settings in Engine Settings to {} From [] ... Json Selector requires use of square brackets.

I did this so as to provide backwards compatibility with existing scripts.

**Comment by saucepleez** [comment]
Furthermore, it will partially work if you replace { } in the script with [ ] but you cannot access array items.
