### ISSUE TITLE
Json Parse Command

### ISSUE THREAD

**Issue by saucepleez** [saucepleez/taskt#68]
Add Command that parses json and allows looping like a list.

Take sample JSON:

 `   {
  'Stores': [
    'Lambton Quay',
    'Willis Street'
  ],
  'Manufacturers': [
    {
      'Name': 'Acme Co',
      'Products': [
        {
          'Name': 'Anvil',
          'Price': 50
        }
      ]
    },
    {
      'Name': 'Contoso',
      'Products': [
        {
          'Name': 'Elbow Grease',
          'Price': 99.95
        },
        {
          'Name': 'Headlight Fluid',
          'Price': 4
        }
      ]
    }
  ]
}`

User can specify something like `$..Products[?(@.Price >= 50)].Name` to get all items above 50 dollars price and loop each item found.

**Comment by atotalnoob** [comment]
Your json is malformed. You have quotes around it

**Comment by saucepleez** [comment]
@atotalnoob 

I copied it from a string object :)

**Comment by merveAltili** [comment]
![image](https://user-images.githubusercontent.com/27894231/61535794-cec01d00-aa3b-11e9-998d-5ced2ef76db8.png)


How do I parse the json expression that appears in this image. Ex: net_total> = 1000 I want to list the descriptions of those.
