### ISSUE TITLE
Error in UI Automation and Click UI Item

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#72]
Hi @saucepleez. Yesterday i'll check my script in last dev-branch version and have error:
`
2018-10-26 08:49:42.785 +03:00 [INF] Running Line 26: Click UI Item [Perform Left Click on 'Физические лица' in Window '[Env.ActiveWindowTitle]']
2018-10-26 08:49:43.719 +03:00 [INF] Result Code: Error
2018-10-26 08:49:43.719 +03:00 [INF] Error: System.Exception: System.FormatException: Входная строка имела неверный формат.
   в System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   в System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   в System.Int32.Parse(String s)
   в taskt.Core.AutomationCommands.SendMouseMoveCommand.RunCommand(Object sender) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 2278
   в taskt.Core.AutomationCommands.ThickAppClickItemCommand.RunCommand(Object sender) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 2459
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 225
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 246
   в taskt.Core.AutomationEngineInstance.ExecuteScript(String filePath) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 110
`

Then i'll try this action by UI Automation and have similar error:
`2018-10-26 08:56:29.883 +03:00 [INF] Running Line 28: UI Automation [Left Click element in window 'Current Window']
2018-10-26 08:56:30.665 +03:00 [INF] Result Code: Error
2018-10-26 08:56:30.665 +03:00 [INF] Error: System.Exception: System.FormatException: Входная строка имела неверный формат.
   в System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   в System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   в System.Int32.Parse(String s)
   в taskt.Core.AutomationCommands.SendMouseMoveCommand.RunCommand(Object sender) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 2278
   в taskt.Core.AutomationCommands.UIAutomationCommand.RunCommand(Object sender) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 2808
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 225
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 246
   в taskt.Core.AutomationEngineInstance.ExecuteScript(String filePath) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 110
`

At first i think that problem in complex window name:
Here it: 

> ТАНАИС / Рубцов Валерий / Управление небольшой фирмой, редакция 1.5 + CRM, редакция 2.0 (1.5.4.34/2.0.9.6). Разработано совместно с "1С-Рарус" тел: +7 (495) 231-20-02 crm@rarus.ru www.rarus.ru

But earler similar command works good in same windows name.

This commands and whole script works great in 1.9.3.0

**Comment by saucepleez** [comment]
Both commands end up using the Mouse Move Command when clicking items.  The UI Automation and Click Item both get the clickable location of the element and then create the Mouse Move Command, set the parameters, then run the command.

However, to this point, Mouse Move could not use variables to move the mouse.  In order to add variable support, the Mouse Move command was updated which changed the parameters from integer to string.  It appears that the command thinks the value being parsed in your command is invalid (AKA not a number).  I have added exception handling so it will output the error specifically with the X and Y values that are attempting to be parsed.

Can you run the latest DEV build and reply with the actual values of the command? I am currently unable to reproduce the issue.

**Comment by msshubin** [comment]
Hi, thanks. I'll heck it in last dev-branch:
`
2018-10-29 08:08:32.551 +03:00 [INF] Running Line 7: Wait For Window To Exist [Target Window: 'Запуск 1С:Предприятия', Wait Up To 600 seconds]
2018-10-29 08:08:32.864 +03:00 [INF] Running Line 8: Click UI Item [Perform Left Click on '{1CDataBase}' in Window 'Запуск 1С:Предприятия']
2018-10-29 08:08:33.223 +03:00 [INF] Result Code: Error
2018-10-29 08:08:33.223 +03:00 [INF] Error: System.Exception: System.Exception: System.Exception: Error parsing input to int type (X: 643, Y:520,5) System.FormatException: Входная строка имела неверный формат.
   в System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   в System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   в System.Int32.Parse(String s)
   в taskt.Core.AutomationCommands.SendMouseMoveCommand.RunCommand(Object sender) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 2272
   в taskt.Core.AutomationCommands.SendMouseMoveCommand.RunCommand(Object sender) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 2276
   в taskt.Core.AutomationCommands.ThickAppClickItemCommand.RunCommand(Object sender) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 2458
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 231
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 252
   в taskt.Core.AutomationCommands.BeginIfCommand.RunCommand(Object sender, ScriptAction parentCommand) в C:\src\taskt\taskt\Core\AutomationCommands.cs:строка 5233
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 200
   в taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 252
   в taskt.Core.AutomationEngineInstance.ExecuteScript(String filePath) в C:\src\taskt\taskt\Core\AutomationEngine.cs:строка 116
`

**Comment by saucepleez** [comment]
can you recapture the command and see if it persists? AFAIK, It is not possible to have fractions in coordinates - screen coordinates are integers (whole number) only.  What I can do is make the number round-down, but im not sure how this scenario is happening.

I will use your debug output posted here to assess and implement a fix.

**Comment by saucepleez** [comment]
I changed the parse method so it should round the variables down -- it should not be possible to move the mouse to a position like 540.5 but it should be better handled now.
