### ISSUE TITLE
WildCards in selector and window names

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#74]
@saucepleez it will be great feature if we can use wildcards like * in Windows names and selectors in browsers and gui. Sometimes window name is dynamic and depends on inner data in application like number or unread messages and so on.

**Comment by saucepleez** [comment]
Ok, once the current build is stabilized, lets assess.  I am going to try to build some better scripts for testing purposes.

**Comment by saucepleez** [comment]
@msshubin After taking a look at source code for Window Commands, if the exact name fails, then it attempts to find the window based on a contains search.  For example, a new Notepad instance is "Untitled - Notepad" but you could use "Untitled" or "Notepad" and it should find the window after initial search fails and it falls back to partial match.  Note the first window found is returned.

      var potentialWindow = System.Diagnostics.Process.GetProcesses().Where(prc => prc.MainWindowTitle.Contains(windowName)).FirstOrDefault();
                if (potentialWindow != null)
                    hWnd = potentialWindow.MainWindowHandle;

If it adds value, we could look at implementing a "Find Windows" command which returns a List of Window Names Found (String List), so then the list can be parsed by Loop or JSON selector

**Comment by msshubin** [comment]
@saucepleez big thanks, i'll check it and selection by windows names truly worked with substring!
What about Web selectors?

**Comment by saucepleez** [comment]
@msshubin

I will review, although I initially suspect there will be some limitation with the web driver.

**Comment by saucepleez** [comment]
Ok so after reviewing, you could use XPath search method to do a partial search.  Take the following html:

    <html>
    <head></head>

    <body>
    <div id=some_id1>Hello</div>
    <div id=some_id2>World</div>
    </body>
    </html>

You can perform a contains search in the search parameter using Find Element By XPath (first result) or Find Elements By XPath (list):

    //*[contains(@id, 'some_id')]

This would return both ID tags because they partially matched.  You can then proceed to loop the variable (assuming you did Find Element**s** by XPath) and output text of each like so:

    {vResults => $.Text}

**Comment by saucepleez** [comment]
Closing since there is some basic level of wildcard searches using XPath.  The driver is going to be limited in other types of partial searches.
