### ISSUE TITLE
Run Custom Code

### ISSUE THREAD

**Issue by andreyofficinal** [saucepleez/taskt#76]
Hello @saucepleez!
Is there any way to insert the variables into code, content of **Run Custom Code** command?
I think, there is major loss of meaning of that command, while user can not make the result dependent on variables.

**Comment by saucepleez** [comment]
@andreyofficinal 

There is currently not a way to do it with that command.  However, there is now an **Execute DLL** command under API Commands that can be used if you have an actual DLL file.  

If you think this command provides value then I will assess how to enhance it further.

**Comment by saucepleez** [comment]
@andreyofficinal 

I have added the ability to pass variables as argument parameters to custom code.  Please see the sample provided in Sample Scripts folder.

**Comment by andreyofficinal** [comment]
@saucepleez Thank you!
