### ISSUE TITLE
DropDown list of variables in Sequence Command

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#77]
@saucepleez, good start to the week!
When i have variables in my script, i can't choose them in Sequence Command in DropDown list, but if i write it manual by [] or {} - all ok! Here:
![image](https://user-images.githubusercontent.com/22539710/47629419-5a171c80-db54-11e8-8c91-3e21a153ad65.png)
![image](https://user-images.githubusercontent.com/22539710/47629428-6602de80-db54-11e8-8059-68e35d5fafa2.png)
![image](https://user-images.githubusercontent.com/22539710/47629440-7fa42600-db54-11e8-9b98-b323e375c638.png)

But if i write it manual it's workt perfect:
![image](https://user-images.githubusercontent.com/22539710/47629467-a82c2000-db54-11e8-9a3b-8003620c6811.png)

I Want to use Sequence Command to simplify big scripts and reuse already writed script blocks.
At this moment it will be great to include TaskT scripts with mapping variables from main script.

**Comment by saucepleez** [comment]
Hello,

I have updated the logic to reflect variables within the sequence command.  I will also look at adding some type of way to "Drag and Drop" commands into an existing sequence command.

**Comment by saucepleez** [comment]
Closing this issue since Drag and Drop is already its own issue: https://github.com/saucepleez/taskt/issues/78
