### ISSUE TITLE
Cut/Copy/Paste/Import in Sequence Command

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#78]
Jason, it will be great if we can drag&drop or cut/copy/paste commands between main script and sequence command in this script, how you think? Or if we can import early generated script into sequence command.

**Comment by saucepleez** [comment]
@msshubin 

Dragging and Dropping commands into Sequence has been added to DEV. Please see Settings screen for "Allow Drag and Drop into Sequence Commands" option, it should be defaulted to `true` initially.

Import Commands has been added to Sequence Command Screen

Sequence Command features a Right Click context menu option - "Move Out To Parent" which will move the command up and out to the parent builder.

**Comment by msshubin** [comment]
Big thanks! It's very useful! But if i place command to sequence:
![image](https://user-images.githubusercontent.com/22539710/47769156-38549b80-dcf4-11e8-8d8d-8a0a819578f6.png)
all ok, but if u now select all commands in sequence, right click and select 'Move out to parent', then sequence reverted commands order:
![image](https://user-images.githubusercontent.com/22539710/47769211-76ea5600-dcf4-11e8-82c5-08f63a923ce6.png)
And don't delete it in sequence:
![image](https://user-images.githubusercontent.com/22539710/47769227-8f5a7080-dcf4-11e8-99b2-fae5419b5431.png)

**Comment by saucepleez** [comment]
Are you sure you pressed "Keep" button?  I will rename them to "Save" and "Close" - if you press close, the changes will revert so you should choose "Keep"

**Comment by msshubin** [comment]
Ok, when i click Keep - sequence saved correctly, but order is reverted

**Comment by msshubin** [comment]
Sorry for so long ) At first i have order of Show Message commands: One, Two, Three, Four
![2018-11-03_07-55-44](https://user-images.githubusercontent.com/22539710/47947856-47c72500-df3e-11e8-995a-c52a77bc4962.png)
![2018-11-03_07-56-33](https://user-images.githubusercontent.com/22539710/47947857-4a297f00-df3e-11e8-8c54-190794c2e10b.png)
Click Keep and then again open sequence.
![2018-11-03_07-57-05](https://user-images.githubusercontent.com/22539710/47947859-4c8bd900-df3e-11e8-86ac-b537d8c4735f.png)
![2018-11-03_07-57-31](https://user-images.githubusercontent.com/22539710/47947860-4eee3300-df3e-11e8-8db5-2166fe924586.png)

Here i have reverted order of Show Message commands: Four, Three, Two, One

**Comment by saucepleez** [comment]
Thanks. I have narrowed this down -- it is occuring only when setting **New Commands Insert Below Selected Command** is set to True.

**Comment by saucepleez** [comment]
Closing Issue
