### ISSUE TITLE
Date format error

### ISSUE THREAD

**Issue by arctocore** [saucepleez/taskt#81]
Getting an error while formatting the date dd/MM/YYYY = -2023 alike.
You should try out the sample: "Data Calculation Sample".

I also tried the other samples out of the box. They failed:

1: DLL sample (replaced with correct dll file)
2: Date calc.
3: Format Date
4: Json parse
5: Regex
6: Web automation

**Comment by saucepleez** [comment]
Hi,

Thanks for reporting this issue.  I have created a hotfix for the issue temporarily.  The real solution is to allow users to define "types" of variable such as "date", "number", etc.  

Also, I will convert the samples and validate into a 2.1 folder for this build.

**Comment by saucepleez** [comment]
Please see deployed changes:

https://github.com/saucepleez/taskt/releases/tag/v2.1.1.0
