### ISSUE TITLE
Error on Web Element Exists If.

### ISSUE THREAD

**Issue by andreyofficinal** [saucepleez/taskt#85]
Hello @saucepleez!
I have found the next bug: using the command **Begin If** with **Web Element Exists** value and if **Find Element By CSS Selector**, I always get the error.
The values are
> Selenium Instance Name | chromelive
> Element Search Method | Find Element By CSS Selector
> Element Search Parameter | [aria-label^="Непрочитанные"]>div>div

The error is
[taskt Engine Logs20181116.txt](https://github.com/saucepleez/taskt/files/2589365/taskt.Engine.Logs20181116.txt)

**Comment by saucepleez** [comment]
Are you using a variable to access the session instance?

**Comment by andreyofficinal** [comment]
No, I always use text name.

**Comment by saucepleez** [comment]
Ok. Is this always occurring or is it intermittent? Also does this error occur only specifically for this command?

**Comment by saucepleez** [comment]
Can you try the updated logic in the dev branch? Let me know if you need a compiled binary.

**Comment by andreyofficinal** [comment]
Ok. Thanks.
It occurs always, every time I chose **Web Element Exists** in **Begin If**. But in **Element Action** it works well.
I'll notify you about the results.

**Comment by saucepleez** [comment]
Closing due to no reply.  Please open a new issue if the problem persists.
