### ISSUE TITLE
Localize TaskT

### ISSUE THREAD

**Issue by msshubin** [saucepleez/taskt#88]
Hi, how i can localize TaskT? I see, that all name in UI specified explicitly. Can we include to TaskT project localization libs and than make locale packages?

**Comment by msshubin** [comment]
Maybe classic resx way?

**Comment by saucepleez** [comment]
Yes, probably using a resx file.  Adding localization will be a lot of work as the resource files will need to be implemented and then the forms will need to be updated to consume the resource files.   Additionally, the AutomationCommands.cs stores the command parameters in English so additional logic is required to make a call to get strings for those as well.

When I built this localization was not anywhere on my radar but I can understand now why you are asking.

**Comment by saucepleez** [comment]
We can look at doing something like this:

https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/y99d1cd3(v=vs.100)

> Set Form Localizable Property to True.

![image](https://user-images.githubusercontent.com/5113950/52825864-718afe80-308c-11e9-9da1-90847ea4dc46.png)

> Change Language to "Russian"

![image](https://user-images.githubusercontent.com/5113950/52825944-ce86b480-308c-11e9-8dc4-aa24542c88ee.png)

> Click on a Control and Change the "Text" property

![image](https://user-images.githubusercontent.com/5113950/52826005-0d1c6f00-308d-11e9-9a75-be5e37c908e7.png)

> Form will be updated like so:

![image](https://user-images.githubusercontent.com/5113950/52826021-20c7d580-308d-11e9-98e4-faa05a7adb68.png)

Are you comfortable giving me the translations? I can try with Google Translate and then you can fix them?

**Comment by saucepleez** [comment]
Attached is sample resx. I used google translate but I am sure it is not correct.

![image](https://user-images.githubusercontent.com/5113950/52827013-1d364d80-3091-11e9-9172-a044c2e2a66f.png)


![image](https://user-images.githubusercontent.com/5113950/52827001-0ee83180-3091-11e9-9ab8-d503a5c055bc.png)
[frmScriptBuilder.ru.resx.txt](https://github.com/saucepleez/taskt/files/2867322/frmScriptBuilder.ru.resx.txt)

**Comment by msshubin** [comment]
wow, it's great! I'll check it and send you resx file. I need just put it to dev folder?

**Comment by saucepleez** [comment]
I have added the file to DEV branch.  You can change the language and update the file from visual studio (double-click `frmScriptBuilder.ru.resx` or provide the required translations here and I will implement them.  Additionally, I may need to tweak some of the controls to better support multi-language.

This effort will ultimately need to be done for each form.  I will also generate the strings into a separate resource file.

**Comment by saucepleez** [comment]
Closing as not taken
