### ISSUE TITLE
Fix Taskt Garbage UI

### ISSUE THREAD

**Issue by atotalnoob** [saucepleez/taskt#93]
Here is that thingie you assigned to me 
[taskt-box (2).zip](https://github.com/saucepleez/taskt/files/2681852/taskt-box.2.zip)

**Comment by saucepleez** [comment]
So, are you saying we need more garbage collection for the UI?

**Comment by atotalnoob** [comment]
I wonder how much garbage trucks cost

**Comment by atotalnoob** [comment]
Cause you'll need one to haul away your garbage ui

**Comment by saucepleez** [comment]
*waits for atotalnoob to develop the angular front end*

*dies*
